import React, { useEffect, useMemo, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import axios from 'axios';

const API = process.env.REACT_APP_API_URL || (process.env.NODE_ENV === 'production' ? '' : 'http://localhost:8000');
type TutorChatMessage = { role: 'user' | 'assistant'; text: string };
let pyodideReady: Promise<any> | null = null;

type SavedState = {
  bookmarks: string[]; notes: { text: string; date: string }[];
  projects: { title: string; github: string }[];
  reports: { url: string; reason: string; status?: string }[]; goal: number; language: string;
  quizScore: number; codePassed: boolean; groups: string[]; placementTasks: string[]; completedChallenges: string[]; challengeDate?: string;
};

const initial: SavedState = { bookmarks: [], notes: [], projects: [], reports: [], goal: 5, language: 'English', quizScore: 0, codePassed: false, groups: [], placementTasks: [], completedChallenges: [] };

const featureInfo: Record<string, { icon: string; title: string; description: string; metrics: [string,string][]; steps: string[]; tip: string }> = {
  recommendation: { icon:'✨', title:'Personalized Recommendations', description:'A learning plan tailored to your education level, college profile and completed lessons.', metrics:[['Learning level','Personalized'],['Plan type','Adaptive'],['Next review','After 3 lessons']], steps:['Review your suggested focus','Open the recommended roadmap','Complete lessons to improve future suggestions'], tip:'Keep your profile and progress updated for more accurate recommendations.' },
  continue: { icon:'▶', title:'Continue Learning', description:'Resume lessons exactly where you stopped and review your recent learning activity.', metrics:[['Recent lessons','Synced locally'],['Progress','Auto tracked'],['History','Last viewed']], steps:['Select a recent lesson','Continue the video or tutorial','Mark it complete when finished'], tip:'Short daily learning sessions are easier to maintain than occasional long sessions.' },
  quiz: { icon:'🧠', title:'Module Quizzes', description:'Check your understanding with short assessments and immediate feedback.', metrics:[['Current score','Live'],['Attempts','Unlimited'],['Feedback','Instant']], steps:['Read the question carefully','Select the best answer','Check the explanation and retry'], tip:'Review the lesson before retrying a question you missed.' },
  coding: { icon:'💻', title:'Coding Practice', description:'Write and run Python or JavaScript directly in your browser.', metrics:[['Languages','Python, JavaScript'],['Execution','Browser-only'],['Input','Supported']], steps:['Choose Python or JavaScript','Write code and optional standard input','Run it and inspect the output'], tip:'Test small inputs first, then add edge cases.' },
  projects: { icon:'🚀', title:'Engineering Projects', description:'Build a verified portfolio by submitting engineering projects hosted on GitHub.', metrics:[['Submitted','Saved locally'],['Repository','GitHub'],['Portfolio','Ready']], steps:['Create a clear project repository','Add a useful README and screenshots','Submit its title and GitHub URL'], tip:'A strong README should explain the problem, solution, setup and results.' },
  certificates: { icon:'🏆', title:'Certificates & Achievements', description:'Track learning milestones, unlock badges and print completion evidence.', metrics:[['Lessons', 'Progress based'],['Current badge','Rising Engineer'],['Certificate','Printable']], steps:['Complete roadmap lessons','Reach the required milestone','Print or save your certificate'], tip:'Complete one full roadmap to create a stronger achievement story.' },
  bookmarks: { icon:'🔖', title:'Saved Resources', description:'Keep important lessons, references and tutorials in one personal collection.', metrics:[['Storage','Local'],['Collection','Personal'],['Access','Instant']], steps:['Save a useful resource','Return to it from this page','Remove items after completing them'], tip:'Bookmark only high-value references so your collection stays useful.' },
  notes: { icon:'📝', title:'Learning Notes', description:'Capture concepts, formulas, questions and revision points while studying.', metrics:[['Notes','Auto saved'],['Privacy','On device'],['Format','Quick notes']], steps:['Write one clear idea per note','Include a question or example','Review notes before quizzes'], tip:'Writing a concept in your own words improves long-term recall.' },
  resume: { icon:'📄', title:'AI-Assisted Resume Builder', description:'Write your own resume while receiving targeted AI suggestions and a live preview.', metrics:[['Author','You'],['Guidance','AI suggestions'],['Preview','Live']], steps:['Add your headline, summary and skills','Generate improvement suggestions','Review the preview and download your draft'], tip:'Use evidence and measurable results instead of generic adjectives.' },
  reports: { icon:'🚩', title:'Content Quality Reports', description:'Report broken, outdated or incorrect course content so learning material stays reliable.', metrics:[['Report types','3'],['Saved reports','Local history'],['Review status','Tracked']], steps:['Paste the exact lesson or video URL','Choose the most accurate issue','Submit and retain the report record'], tip:'Add the exact affected resource URL so the issue can be reproduced quickly.' },
  goals: { icon:'🎯', title:'Weekly Goals & Notifications', description:'Set a realistic weekly lesson target and enable reminders to remain consistent.', metrics:[['Target','Adjustable'],['Frequency','Weekly'],['Reminder','Browser']], steps:['Choose lessons per week','Enable browser reminders','Review progress at week end'], tip:'A sustainable goal you meet every week is better than an ambitious one you abandon.' },
  languages: { icon:'🌐', title:'Regional Language Learning', description:'Choose your preferred lesson language for a more comfortable learning experience.', metrics:[['Languages','8'],['Preference','Saved'],['Content','Expanding']], steps:['Select your preferred language','Use translated lesson resources','Change language whenever needed'], tip:'Technical terms may remain in English to keep them industry-relevant.' },
  offline: { icon:'📱', title:'Mobile & Offline Learning', description:'Install Engineer Made on your device and keep essential learning tools available with weak connectivity.', metrics:[['Layout','Responsive'],['Core shell','Cached'],['Sync','When online']], steps:['Open Engineer Made in Chrome','Choose Install app from the browser menu','Open installed lessons and reconnect to sync'], tip:'Download or open important resources before travelling or losing connectivity.' },
  'ai-tutor': { icon:'🤖', title:'AI Engineering Tutor', description:'Ask technical questions and receive guided explanations, examples and suggested next steps.', metrics:[['Subjects','All engineering'],['Mode','Guided learning'],['Availability','Local demo']], steps:['Enter a focused technical question','Review the explanation and example','Ask a follow-up or open the related roadmap'], tip:'Include the subject, current level and exact point of confusion in your question.' },
  assessment: { icon:'🧩', title:'Adaptive Skill Assessments', description:'Measure current skills and receive a recommended learning level based on your answers.', metrics:[['Questions','Adaptive'],['Result','Instant'],['Plan','Skill based']], steps:['Choose an answer to each question','Submit your assessment','Use the result to select your next roadmap'], tip:'Answer honestly—the result is useful only when it reflects your current ability.' },
  groups: { icon:'👥', title:'Collaborative Study Groups', description:'Create or join focused peer groups for roadmaps, projects and exam preparation.', metrics:[['Group size','2–8 learners'],['Activity','Collaborative'],['Storage','Local demo']], steps:['Name the study group','Choose a common learning goal','Create the group and invite classmates'], tip:'Groups work best with a fixed weekly meeting and a shared goal.' },
  simulations: { icon:'⚙️', title:'Engineering Simulations', description:'Explore circuit and mechanical behaviour by changing inputs and observing calculated outputs.', metrics:[['Labs','Circuit & mechanics'],['Inputs','Interactive'],['Results','Live']], steps:['Choose a simulation','Adjust the input controls','Compare the calculated result with your prediction'], tip:'Predict the output before moving a control to strengthen engineering intuition.' },
  interviews: { icon:'🎙️', title:'Mock Interviews', description:'Practise technical and behavioural interview questions with structured self-evaluation.', metrics:[['Question bank','Mixed'],['Timer','Practice'],['Feedback','Checklist']], steps:['Read the interview question','Prepare and record your response notes','Compare it against the answer checklist'], tip:'Use the STAR structure for behavioural questions: Situation, Task, Action, Result.' },
  placement: { icon:'🎓', title:'Placement Preparation', description:'Track the essential tasks required for campus placements and graduate hiring.', metrics:[['Checklist','6 stages'],['Progress','Tracked'],['Focus','Job readiness']], steps:['Complete profile and resume tasks','Practise aptitude and technical topics','Finish mock interviews before applying'], tip:'Treat placement preparation as a weekly routine, not a last-minute activity.' },
  'repo-analysis': { icon:'🔎', title:'GitHub Repository Analysis', description:'Review repository quality using practical portfolio-readiness checks.', metrics:[['Checks','README & structure'],['Input','GitHub URL'],['Result','Instant review']], steps:['Paste a public GitHub repository URL','Run the portfolio readiness check','Fix the suggested repository improvements'], tip:'Recruiters should understand the project’s value within the first minute.' },
  leaderboard: { icon:'🥇', title:'College Leaderboards', description:'Compare learning activity through points earned from lessons, quizzes and projects.', metrics:[['Ranking','Weekly'],['Points','Activity based'],['Scope','College']], steps:['Complete lessons and quizzes','Submit portfolio projects','Return weekly to review ranking'], tip:'Use rankings for motivation, but measure success by skills gained.' },
  analytics: { icon:'📈', title:'Advanced Learning Analytics', description:'Understand progress, consistency, assessment performance and portfolio readiness.', metrics:[['Progress','Real-time'],['Insights','Multi-signal'],['Audience','Learner & admin']], steps:['Review your activity summary','Identify the weakest learning signal','Choose one improvement action for this week'], tip:'Track trends over several weeks instead of reacting to one day of activity.' },
  'skill-tree': { icon:'🌳', title:'Engineering Skill Tree', description:'See the skills you unlock as you complete your selected engineering roadmap.', metrics:[['Track','Role focused'],['Progress','Live'],['Milestones','Unlocked']], steps:['Complete lessons in your selected track','Unlock the next skill milestone','Use locked skills to plan your next study session'], tip:'Build foundations before jumping to advanced tools or projects.' },
  'adaptive-practice': { icon:'🎯', title:'Adaptive Practice & Mistake Analysis', description:'Practise an engineering decision, receive immediate feedback, and focus the next attempt on the weak area.', metrics:[['Difficulty','Adaptive'],['Feedback','Instant'],['Focus','Weak skills']], steps:['Answer the scenario','Review the feedback','Use the recommended revision action'], tip:'Do not only retry a question—understand which engineering principle caused the mistake.' },
  'weakness-heatmap': { icon:'🗺️', title:'Weakness Heatmap', description:'A clear map of the skills that need attention based on your learning, assessment and portfolio signals.', metrics:[['Signals','4'],['Scope','Your roadmap'],['Action','Focused']], steps:['Review the red and amber skills','Open one weak skill for revision','Retake practice after studying'], tip:'Choose one weak skill at a time; focused improvement beats scattered revision.' },
  'daily-challenge': { icon:'⚡', title:'Daily Engineering Challenge', description:'Complete one small, role-relevant task every day to keep your learning momentum active.', metrics:[['Frequency','Daily'],['Time','15 minutes'],['Reward','Momentum']], steps:['Read today’s challenge','Complete it before moving on','Return tomorrow for a new challenge'], tip:'Consistency is more valuable than waiting for the perfect long study session.' },
  'ai-summarizer': { icon:'🧾', title:'AI Engineering Summarizer', description:'Turn technical notes, documentation or lesson text into concise revision points.', metrics:[['Input','Your text'],['Output','Revision notes'],['Mode','AI assisted']], steps:['Paste the concept or notes','Ask for a clear summary','Save useful points in Learning Notes'], tip:'Provide the source context and the target level for more useful summaries.' },
  cheatsheet: { icon:'🗒️', title:'Engineering Cheatsheet Generator', description:'Generate a compact revision checklist for a topic in your selected engineering role.', metrics:[['Format','Quick revision'],['Topic','Your choice'],['Output','Copyable']], steps:['Enter one focused topic','Generate a concise cheatsheet','Review it before practice or interviews'], tip:'Use cheatsheets for recall, then return to the full lesson for deep understanding.' },
  'career-explorer': { icon:'🧭', title:'Engineering Career Explorer', description:'Understand the skills, portfolio evidence and entry-level direction for your selected engineering role.', metrics:[['Role','Selected roadmap'],['Focus','Career-ready'],['Next step','Projects']], steps:['Review your selected role','Compare the readiness areas','Choose one skill or project to build next'], tip:'A role becomes credible when you can show projects, not only course completion.' },
  'job-readiness': { icon:'📐', title:'Job Readiness Predictor', description:'A transparent readiness estimate based on your completed lessons, assessment attempts, projects and placement tasks.', metrics:[['Model','Transparent'],['Signals','4'],['Action','Next best step']], steps:['Review the readiness signals','Improve the lowest signal','Recheck after completing meaningful work'], tip:'This is a preparation indicator, not a prediction of hiring outcomes.' },
  'doubt-upload': { icon:'📷', title:'Code, Diagram & Circuit Doubts', description:'Attach a reference locally, explain exactly where you are stuck, and get a structured engineering explanation from the AI tutor.', metrics:[['Formats','Image, PDF, code'],['Input','Private session'],['Help','Guided']], steps:['Attach a relevant reference','Describe the expected and actual result','Ask for a step-by-step explanation'], tip:'A clear description of inputs, expected output and error message produces the strongest technical help.' },
};

export default function LearningHub({ embedded = false, activeFeature, onFeatureChange }: { embedded?: boolean; activeFeature?: string; onFeatureChange?: (feature: string) => void }) {
  const { user, loading, profile, completedLessons, bookmarks, removeBookmark, assessmentAttempts, recordAssessment } = useAuth();
  const storageKey = `engineer-made-hub:${user?.uid || 'guest'}`;
  const [state, setState] = useState<SavedState>(() => {
    const today = new Date().toISOString().slice(0, 10);
    try {
      const saved = { ...initial, ...JSON.parse(localStorage.getItem(storageKey) || '{}') } as SavedState;
      return saved.challengeDate === today ? saved : { ...saved, completedChallenges: [], challengeDate: today };
    } catch { return { ...initial, challengeDate: today }; }
  });
  const [note, setNote] = useState('');
  const [projectTitle, setProjectTitle] = useState(''); const [github, setGithub] = useState(''); const [projectError, setProjectError] = useState('');
  const [reportUrl, setReportUrl] = useState(''); const [reportReason, setReportReason] = useState('');
  const [codeLanguage, setCodeLanguage] = useState<'python' | 'javascript'>('python'); const [code, setCode] = useState('print("Hello Engineer")'); const [codeInput, setCodeInput] = useState(''); const [codeOutput, setCodeOutput] = useState('Ready to run in your browser.'); const [codeBusy, setCodeBusy] = useState(false);
  const [isListening, setIsListening] = useState(false); const [installPrompt, setInstallPrompt] = useState<any>(null); const [openedNote, setOpenedNote] = useState<{ text:string; date:string } | null>(null);
  const [quizChoice, setQuizChoice] = useState('');
  const [tutorQuestion, setTutorQuestion] = useState('');
  const [tutorMessages, setTutorMessages] = useState<TutorChatMessage[]>([{role:'assistant',text:'Namaste! 👋 I’m your AI Engineering Tutor. Ask me about engineering concepts, exam preparation, projects, careers, or college guidance. You can type or use the microphone in English, Hindi, or Hinglish.'}]);
  const [tutorBusy, setTutorBusy] = useState(false); const [tutorError, setTutorError] = useState('');
  const [assessmentChoice, setAssessmentChoice] = useState(''); const [assessmentResult, setAssessmentResult] = useState('');
  const [certificateCode, setCertificateCode] = useState(''); const [certificateError, setCertificateError] = useState(''); const [issuingCertificate, setIssuingCertificate] = useState(false);
  const [groupName, setGroupName] = useState(''); const [voltage, setVoltage] = useState(12); const [resistance, setResistance] = useState(6);
  const [interviewAnswer, setInterviewAnswer] = useState(''); const [repoUrl, setRepoUrl] = useState(''); const [repoResult, setRepoResult] = useState(''); const [repoRubric, setRepoRubric] = useState<any>(null); const [repoBusy, setRepoBusy] = useState(false);
  const [practiceChoice, setPracticeChoice] = useState(''); const [practiceResult, setPracticeResult] = useState('');
  const [smartTopic, setSmartTopic] = useState(''); const [smartResult, setSmartResult] = useState(''); const [smartBusy, setSmartBusy] = useState(false);
  const [doubtKind, setDoubtKind] = useState('Code issue'); const [doubtDescription, setDoubtDescription] = useState(''); const [doubtFileName, setDoubtFileName] = useState(''); const [doubtFile, setDoubtFile] = useState<File | null>(null); const [doubtPreview, setDoubtPreview] = useState(''); const [doubtResult, setDoubtResult] = useState(''); const [doubtBusy, setDoubtBusy] = useState(false);
  const [resumeHeadline, setResumeHeadline] = useState(''); const [resumeSummary, setResumeSummary] = useState(''); const [resumeSkills, setResumeSkills] = useState(''); const [resumeSuggestions, setResumeSuggestions] = useState(''); const [resumeBusy, setResumeBusy] = useState(false); const [resumeError, setResumeError] = useState('');
  const [dailyStatus, setDailyStatus] = useState<{ xp: number; streak: number } | null>(null); const [dailyError, setDailyError] = useState('');
  const history = useMemo(() => { try { return JSON.parse(localStorage.getItem('engineer-made-history') || '[]'); } catch { return []; } }, []);
  const save = (next: SavedState) => { setState(next); localStorage.setItem(storageKey, JSON.stringify(next)); };
  const recommendation = profile?.educationStatus === 'Graduated' ? 'Industry-ready projects and interview preparation' : profile?.educationStatus === 'PG' ? 'Advanced specialization and research projects' : 'Foundation-first roadmap with guided projects';
  useEffect(() => { const capture = (event:any) => { event.preventDefault(); setInstallPrompt(event); }; window.addEventListener('beforeinstallprompt', capture); return () => window.removeEventListener('beforeinstallprompt', capture); }, []);

  if (loading) return <div className="loading"><div className="spinner" /></div>;
  if (!user) return <Navigate to="/login" replace />;

  const addNote = () => { if (!note.trim()) return; save({ ...state, notes: [{ text: note.trim(), date: new Date().toLocaleDateString() }, ...state.notes] }); setNote(''); };
  const addProject = () => {
    const repositoryUrl = github.trim();
    if (!projectTitle.trim()) { setProjectError('Enter a project title.'); return; }
    if (!/^https:\/\/(?:www\.)?github\.com\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+(?:\.git)?\/?$/i.test(repositoryUrl)) { setProjectError('Enter a valid GitHub repository URL.'); return; }
    save({ ...state, projects: [{ title: projectTitle.trim(), github: repositoryUrl }, ...state.projects] }); setProjectTitle(''); setGithub(''); setProjectError('');
  };
  const report = async () => {
    if (!reportUrl || !reportReason) return;
    try {
      const token = await user.getIdToken();
      await axios.post(`${API}/api/reports`, { resourceUrl: reportUrl, issueType: reportReason.toLowerCase().replace(/\s+/g, '_') }, { headers: { Authorization: `Bearer ${token}` } });
      save({ ...state, reports: [{ url: reportUrl, reason: reportReason, status: 'Submitted for review' }, ...state.reports] });
      setReportUrl(''); setReportReason('');
    } catch (error: any) { setTutorError(error?.response?.data?.detail || 'The report could not be submitted. Please retry.'); }
  };
  const codeTemplates = { python:'print("Hello Engineer")', javascript:'console.log("Hello Engineer");' };
  const changeCodeLanguage = (language: 'python' | 'javascript') => { setCodeLanguage(language); setCode(codeTemplates[language]); setCodeOutput('Ready to run in your browser.'); };
  const runCode = async () => {
    if (!code.trim() || codeBusy) return;
    setCodeBusy(true); setCodeOutput(codeLanguage === 'python' ? 'Loading the free Python runtime…' : 'Running JavaScript…');
    try {
      if (codeLanguage === 'javascript') { const output:string[] = []; const write = (...items:any[]) => output.push(items.map(String).join(' ')); const result = new Function('console', 'input', code)({ log:write, error:write, warn:write }, codeInput); if (result !== undefined) write(result); setCodeOutput(output.join('\n') || 'Program finished with no output.'); }
      else {
        const loader = (window as any).loadPyodide;
        if (!loader) throw new Error('Python is still downloading. Check your connection, wait a moment, then run again.');
        pyodideReady ||= loader({ indexURL:'https://cdn.jsdelivr.net/pyodide/v314.0.6/full/' });
        const runtime = await pyodideReady; runtime.globals.set('user_code', code); runtime.globals.set('user_stdin', codeInput);
        const output = await runtime.runPythonAsync("import io, sys, traceback\n_capture = io.StringIO()\n_stdout, _stdin = sys.stdout, sys.stdin\nsys.stdout, sys.stdin = _capture, io.StringIO(user_stdin)\ntry:\n    exec(user_code, {})\nexcept Exception:\n    traceback.print_exc(file=_capture)\nfinally:\n    sys.stdout, sys.stdin = _stdout, _stdin\n_capture.getvalue() or 'Program finished with no output.'");
        setCodeOutput(String(output));
      }
      save({ ...state, codePassed:true });
    } catch (error:any) { setCodeOutput(error?.message || String(error)); }
    finally { setCodeBusy(false); }
  };
  const checkQuiz = () => save({ ...state, quizScore: quizChoice === 'feedback' ? 100 : 0 });
  const finishAssessment = async () => {
    if (!assessmentChoice) { setAssessmentResult('Choose an answer before finishing the assessment.'); return; }
    const score = assessmentChoice === 'prototype' ? 100 : assessmentChoice === 'theory' ? 45 : 20;
    const level = score >= 80 ? 'Intermediate' : 'Foundation';
    await recordAssessment(score, level);
    setAssessmentResult(score >= 80 ? 'Strong applied-thinking signal · Recommended level: Intermediate' : 'Foundation review recommended · Focus on testing and validation');
  };
  const issueCertificate = async () => {
    if (completedLessons.length < 10) { setCertificateError('Complete at least 10 lessons to unlock a verified certificate.'); return; }
    setIssuingCertificate(true); setCertificateError('');
    try {
      const token = await user.getIdToken();
      const response = await axios.post(`${API}/api/certificates/issue`, { track_title: 'Engineer Made learning milestone' }, { headers: { Authorization: `Bearer ${token}` } });
      setCertificateCode(response.data.code);
    } catch (error: any) { setCertificateError(error?.response?.data?.detail || 'The certificate service is temporarily unavailable.'); }
    finally { setIssuingCertificate(false); }
  };
  const askTutor = async (suggested?: string) => {
    const question = (suggested || tutorQuestion).trim(); if (!question || tutorBusy) return;
    const next = [...tutorMessages, {role:'user' as const,text:question}]; setTutorMessages(next); setTutorQuestion(''); setTutorBusy(true); setTutorError('');
    try { const response = await axios.post(`${API}/api/ai-tutor/chat`, {message:question,history:tutorMessages,learner_name:profile?.name || user.displayName || 'Engineer'}); setTutorMessages([...next,{role:'assistant',text:response.data.answer}]); }
    catch (error:any) { setTutorError(error?.response?.data?.detail || 'The tutor could not respond. Check that the backend is running and Gemini is configured.'); }
    finally { setTutorBusy(false); }
  };
  const speak = (text:string) => { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.rate=.95; window.speechSynthesis.speak(utterance); };
  const startVoice = async () => {
    const Recognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!Recognition) { setTutorError('Voice input is not supported in this browser. Use the latest Chrome or Edge, or type your question.'); return; }
    if (!navigator.mediaDevices?.getUserMedia) { setTutorError('This browser cannot access a microphone. Use the latest Chrome or Edge, or type your question.'); return; }

    setTutorError('');
    let stream: MediaStream | null = null;
    let receivedTranscript = false;
    let receivedError = false;
    const stopMicrophone = () => stream?.getTracks().forEach(track => track.stop());

    try {
      // Request the selected microphone first so a device/busy/permission error
      // is reported clearly before Chrome's speech service starts.
      stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      stopMicrophone();
      stream = null;
      const recognition = new Recognition();
      recognition.lang = 'en-IN';
      recognition.interimResults = false;
      recognition.continuous = false;
      recognition.maxAlternatives = 1;
      recognition.onresult = (event: any) => {
        receivedTranscript = true;
        setTutorQuestion(event.results[0][0].transcript);
      };
      recognition.onerror = (event: any) => {
        receivedError = true;
        const errors: Record<string, string> = {
          'not-allowed': 'Microphone access was denied by the browser. Check the site permission, then reload.',
          'service-not-allowed': 'Chrome speech recognition is disabled. Check Chrome microphone and speech service settings.',
          'audio-capture': 'Chrome cannot use the selected microphone. Close any app using it, select another microphone, then retry.',
          'network': 'Chrome could not reach its speech-recognition service. Check your internet connection and retry.',
          'no-speech': 'No speech was detected. Press the microphone and speak clearly after it starts.',
          'aborted': 'Voice input was interrupted. Close other microphone apps and retry.',
        };
        setTutorError(errors[event.error] || `Voice input failed (${event.error || 'unknown error'}). Type your question or retry.`);
      };
      recognition.onend = () => { setIsListening(false);
        stopMicrophone();
        if (!receivedTranscript && !receivedError) setTutorError('No speech was detected. Press the microphone and speak after it starts.');
      };
      setIsListening(true); recognition.start();
    } catch (error: any) {
      stopMicrophone(); setIsListening(false);
      const name = error?.name || '';
      if (name === 'NotAllowedError' || name === 'SecurityError') setTutorError('Chrome could not access the microphone. Check the site permission and Windows microphone privacy settings, then reload.');
      else if (name === 'NotFoundError') setTutorError('No microphone was found. Connect or select a microphone in Chrome settings, then retry.');
      else if (name === 'NotReadableError') setTutorError('The microphone is busy or unavailable. Close Teams, Meet, Discord, or another microphone app, then retry.');
      else setTutorError('Microphone setup failed. Type your question or retry after checking your microphone device.');
    }
  };
  const installApp = async () => { if (!installPrompt) return; installPrompt.prompt(); await installPrompt.userChoice; setInstallPrompt(null); };
  const downloadNote = (saved:{text:string;date:string}) => { const page = window.open('', '_blank'); if (!page) return; page.document.write(`<title>Engineer Made note</title><main><h1>Learning note</h1><p>${saved.date}</p><article>${saved.text.replace(/</g,'&lt;').replace(/\n/g,'<br>')}</article></main><style>body{font:16px Georgia,serif;padding:40px;color:#171717}h1{margin-bottom:6px}p{color:#666}article{white-space:normal;line-height:1.6;border-top:1px solid #ddd;padding-top:24px}</style>`); page.document.close(); page.focus(); page.print(); };
  const downloadResume = () => {
    const text = `${profile?.name || user.displayName}\n${resumeHeadline}\n${profile?.email || user.email}\n${profile?.collegeName || ''}\n\nSUMMARY\n${resumeSummary}\n\nSKILLS\n${resumeSkills}\n\nPROJECTS\n${state.projects.map(p => `- ${p.title}: ${p.github}`).join('\n') || 'Add GitHub projects in the Projects section.'}\n\nLEARNING\n${completedLessons.length} lessons completed in Engineer Made`;
    const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = 'engineering-resume.txt'; a.click(); URL.revokeObjectURL(url);
  };
  const generateResumeSuggestions = async () => {
    const draft = `Candidate: ${profile?.name || user.displayName || 'Engineering student'}\nHeadline: ${resumeHeadline}\nSummary: ${resumeSummary}\nSkills: ${resumeSkills}\nProjects: ${state.projects.map(project => project.title).join(', ') || 'None yet'}`;
    if (!resumeHeadline.trim() && !resumeSummary.trim() && !resumeSkills.trim()) { setResumeError('Write at least one resume section before asking for suggestions.'); return; }
    setResumeBusy(true); setResumeError(''); setResumeSuggestions('');
    try { const response = await axios.post(`${API}/api/ai-tutor/chat`, { message:`Review this engineering student resume draft. Give 5 concise, honest improvements. Do not invent experience, achievements, marks, or skills.\n\n${draft}`, history: [], learner_name: profile?.name || user.displayName || 'Engineer' }); setResumeSuggestions(response.data.answer); }
    catch (error: any) { setResumeError(error?.response?.data?.detail || 'AI suggestions are unavailable. Check the Gemini service and retry.'); }
    finally { setResumeBusy(false); }
  };
  const runAdaptivePractice = async () => {
    if (!practiceChoice) { setPracticeResult('Choose an answer first.'); return; }
    const score = practiceChoice === 'validate' ? 100 : practiceChoice === 'measure' ? 60 : 20;
    await recordAssessment(score, score >= 80 ? 'Applied practice' : 'Foundation review');
    setPracticeResult(score === 100 ? 'Correct. Validation with measurable evidence is the strongest engineering decision.' : 'Revision focus: define a measurable test, then validate the result before concluding.');
  };
  const generateStudyAsset = async (kind: 'summary' | 'cheatsheet') => {
    if (!smartTopic.trim() || smartBusy) return;
    setSmartBusy(true); setSmartResult(''); setTutorError('');
    const instruction = kind === 'summary' ? `Summarize this for an engineering learner in 5 clear bullet points, including one practical example: ${smartTopic}` : `Create a concise engineering revision cheatsheet for this topic. Include key concepts, a mini checklist, one common mistake, and one practical example: ${smartTopic}`;
    try { const response = await axios.post(`${API}/api/ai-tutor/chat`, { message: instruction, history: [], learner_name: profile?.name || user.displayName || 'Engineer' }); setSmartResult(response.data.answer); }
    catch (error: any) { setTutorError(error?.response?.data?.detail || 'Gemini could not create this study asset. Please retry after checking the AI service configuration.'); }
    finally { setSmartBusy(false); }
  };
  const selectDoubtReference = (file?: File) => {
    setDoubtFile(file || null); setDoubtFileName(file?.name || ''); setDoubtPreview('');
    if (file?.type.startsWith('image/')) { const reader = new FileReader(); reader.onload = () => setDoubtPreview(String(reader.result || '')); reader.readAsDataURL(file); }
  };
  const askDoubtTutor = async () => {
    if (!doubtDescription.trim() || doubtBusy) return;
    setDoubtBusy(true); setDoubtResult('');
    const prompt = `Act as an engineering tutor. The learner has a ${doubtKind.toLowerCase()}${doubtFileName ? ` and attached a local reference named ${doubtFileName}` : ''}. Their description: ${doubtDescription}. Explain likely causes, a step-by-step diagnostic approach, and one safe next action.`;
    try {
      if (doubtFile) { const form = new FormData(); form.append('file', doubtFile); form.append('context', doubtDescription); form.append('doubt_kind', doubtKind); const token = await user.getIdToken(); const response = await axios.post(`${API}/api/ai-tutor/vision`, form, { headers:{ Authorization:`Bearer ${token}` } }); setDoubtResult(response.data.answer); }
      else { const response = await axios.post(`${API}/api/ai-tutor/chat`, { message: prompt, history: [], learner_name: profile?.name || user.displayName || 'Engineer' }); setDoubtResult(response.data.answer); }
    }
    catch { setDoubtResult('Start by writing the expected result, actual result, inputs and constraints. Isolate one variable at a time, verify units or error output, then test the smallest reproducible example.'); }
    finally { setDoubtBusy(false); }
  };
  const analyseRepository = async () => {
    if (!repoUrl.trim() || repoBusy) return;
    setRepoBusy(true); setRepoResult(''); setRepoRubric(null);
    try { const token = await user.getIdToken(); const response = await axios.post(`${API}/api/github/repository-analysis`, { url:repoUrl }, { headers:{ Authorization:`Bearer ${token}` } }); setRepoRubric(response.data); }
    catch (error:any) { setRepoResult(error?.response?.data?.detail || 'GitHub analysis is unavailable. Check the public repository URL and retry.'); }
    finally { setRepoBusy(false); }
  };

  const show = (feature: string) => !activeFeature || activeFeature === feature;
  const details = activeFeature ? featureInfo[activeFeature] : undefined;
  const dailyTasks = [
    { id:'daily-concept', icon:'🧠', title:'Review one core engineering concept', xp:20, target:'quiz' },
    { id:'daily-practice', icon:'🎯', title:'Complete one adaptive practice task', xp:30, target:'adaptive-practice' },
    { id:'daily-portfolio', icon:'🚀', title:'Improve one portfolio or project detail', xp:25, target:'projects' },
  ];
  const completeChallenge = async (id: string) => {
    if (state.completedChallenges.includes(id)) return;
    setDailyError('');
    try {
      const token = await user.getIdToken();
      const response = await axios.post(`${API}/api/learner/daily-challenges/complete`, { challenge_id:id }, { headers:{ Authorization:`Bearer ${token}` } });
      save({ ...state, completedChallenges:[...state.completedChallenges, id], challengeDate: response.data.date || new Date().toISOString().slice(0, 10) });
      setDailyStatus({ xp:response.data.xp, streak:response.data.streak });
    } catch (error: any) { setDailyError(error?.response?.data?.detail || 'Daily challenge progress could not be saved. Please retry.'); }
  };
  return <div className={`hub-page ${embedded ? 'hub-embedded feature-workspace' : ''}`}>
    {!embedded && <header className="hub-header"><span className="dashboard-kicker">ENGINEERING CAREER HUB</span><h1>Learn, practise, build and get hired</h1><p>All your learning tools in one local workspace.</p></header>}
    {details && activeFeature !== 'ai-tutor' && <><header className="feature-detail-hero"><div className="feature-hero-icon">{details.icon}</div><div><span className="dashboard-kicker">LEARNER TOOL</span><h1>{details.title}</h1><p>{details.description}</p></div></header><div className="feature-metrics">{details.metrics.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div></>}
    <div key={activeFeature || 'all-tools'} className={activeFeature ? `feature-detail-layout feature-switch ${activeFeature === 'ai-tutor' ? 'tutor-full-layout' : ''}` : ''}><div className={`hub-grid ${activeFeature ? 'single-feature' : ''}`}>
      {show('recommendation') && <section className="hub-card hub-wide"><h2>✨ Personalized recommendation</h2><h3>{recommendation}</h3><p>Based on your {profile?.educationStatus || 'learner'} profile at {profile?.collegeName || 'your college'}.</p><Link to="/paths" className="hub-link">Choose a recommended roadmap →</Link></section>}
      {show('continue') && <section className="hub-card hub-wide"><h2>▶ Continue learning</h2>{history.length ? history.slice(0,3).map((item:any) => <Link key={item.url} to={item.url}>{item.title}</Link>) : <p>Open a lesson to start your history.</p>}<h2 className="recent-heading">🕘 Recently watched</h2><p>{history.length} recent lessons</p>{history.slice(0,4).map((item:any) => <small key={item.url}>{item.title}</small>)}</section>}
      {show('quiz') && <section className="hub-card hub-wide"><h2>🧠 Module quiz & flashcards</h2><p>Complete a roadmap module first, then use these questions and five practice programs to check the concepts you learned.</p><p>What helps an engineer improve a design?</p><select value={quizChoice} onChange={e=>setQuizChoice(e.target.value)}><option value="">Choose an answer</option><option value="guess">Ignoring test results</option><option value="feedback">Testing and feedback</option><option value="copy">Copying without analysis</option></select><button onClick={checkQuiz}>Check answer</button>{state.quizScore > 0 && <b className="success">Correct — 100%</b>}<div className="flashcard-grid"><article><b>Q: What is validation?</b><p>A: Testing a result against a measurable requirement.</p></article><article><b>Q: Why use small tests first?</b><p>A: They isolate errors before a system becomes complex.</p></article><article><b>Q: What should a project README show?</b><p>A: Problem, setup, solution, and evidence of results.</p></article></div><h3>Five module practice programs</h3><ol><li>Print your selected roadmap role.</li><li>Read two numbers and print their sum.</li><li>Find the largest value in a list.</li><li>Validate whether an input is empty.</li><li>Build a small menu using conditions.</li></ol><button onClick={()=>onFeatureChange?.('coding')}>Open coding practice →</button></section>}
      {show('coding') && <section className="hub-card hub-wide compiler-workspace"><header><div><h2>💻 Free browser coding practice</h2><p>Python and JavaScript run directly in your browser. No server, VPS, API key, or payment is required.</p></div><select value={codeLanguage} onChange={e=>changeCodeLanguage(e.target.value as 'python' | 'javascript')}><option value="python">Python</option><option value="javascript">JavaScript</option></select></header><div className="compiler-split"><section><label>Code editor</label><textarea className="code-editor" value={code} onChange={e=>setCode(e.target.value)} spellCheck={false} /><label>Standard input (optional)</label><textarea className="compiler-input" value={codeInput} onChange={e=>setCodeInput(e.target.value)} placeholder="Input passed to your program" /></section><section className="compiler-console"><label>Output</label><pre>{codeOutput}</pre><button onClick={runCode} disabled={codeBusy || !code.trim()}>{codeBusy ? 'Running…' : 'Run code ▶'}</button></section></div></section>}
      {show('projects') && <section className="hub-card hub-wide"><h2>🚀 GitHub projects</h2><div className="resume-grid"><div><input placeholder="Project title" value={projectTitle} onChange={e=>setProjectTitle(e.target.value)} /><input placeholder="https://github.com/user/repo" value={github} onChange={e=>setGithub(e.target.value)} /><button onClick={addProject}>Add to my private project list</button>{projectError && <div className="tutor-error">⚠ {projectError}</div>}</div><aside className="resume-preview"><small>PRIVATE PROJECTS · ONLY YOU</small>{state.projects.length ? state.projects.map(p=><a href={p.github} target="_blank" rel="noreferrer" key={p.github}><b>{p.title}</b><small>{p.github}</small></a>) : <p>Your GitHub projects will be listed here after you add them.</p>}</aside></div></section>}
      {show('certificates') && <section className="hub-card"><h2>🏆 Certificates & badges</h2><strong className="big-number">{completedLessons.length}</strong><p>lessons completed · {Math.max(0,10-completedLessons.length)} until verified certificate</p><span className="badge">{completedLessons.length >= 10 ? 'Roadmap Explorer' : 'Rising Engineer'}</span><button onClick={issueCertificate} disabled={issuingCertificate || completedLessons.length < 10}>{issuingCertificate ? 'Creating credential…' : 'Create verified certificate'}</button>{certificateCode && <div className="result-panel"><b>Credential created: {certificateCode}</b><p>Share this verification link with employers or colleges.</p><Link to={`/verify-certificate/${certificateCode}`}>Verify this certificate →</Link><button onClick={()=>window.print()}>Print certificate</button></div>}{certificateError && <div className="tutor-error">⚠ {certificateError}</div>}<Link to="/verify-certificate" className="hub-link">Verify an existing certificate →</Link></section>}
      {show('bookmarks') && <section className="hub-card"><h2>🔖 Saved courses & bookmarks</h2><p>Save any lesson from its lesson page. Your collection syncs to your signed-in profile.</p>{bookmarks.length ? bookmarks.map(bookmark=><div className="activity-row" key={bookmark.id}><span>🔖</span><div><Link to={bookmark.url}><b>{bookmark.title}</b></Link><small>Saved {new Date(bookmark.savedAt).toLocaleDateString()}</small></div><button onClick={()=>removeBookmark(bookmark.id)}>Remove</button></div>) : <div className="empty-state">No saved lessons yet. Open a lesson and select “Save lesson”.</div>}</section>}
      {show('notes') && <section className="hub-card hub-wide"><h2>📝 Notes library</h2><textarea placeholder="Write a learning note…" value={note} onChange={e=>setNote(e.target.value)} /><button onClick={addNote}>Save note</button><div className="note-library">{state.notes.map((n,i)=><article className="note-paper" tabIndex={0} onClick={()=>setOpenedNote(n)} onKeyDown={e=>e.key==='Enter'&&setOpenedNote(n)} key={`${n.date}-${i}`}><span>📄</span><div><b>{n.text.split(/\s+/).slice(0,6).join(' ')}</b><small>Saved {n.date} · Open note</small></div></article>)}{!state.notes.length && <p className="empty-state">Your saved notes will appear here as papers.</p>}</div>{openedNote && <div className="result-panel"><header><b>Opened note · {openedNote.date}</b><button onClick={()=>downloadNote(openedNote)}>Download as PDF</button><button onClick={()=>setOpenedNote(null)}>Close</button></header><p>{openedNote.text}</p></div>}</section>}
      {show('resume') && <section className="hub-card hub-wide resume-builder"><header><div><h2>📄 Build your resume</h2><p>You write the content. AI only suggests improvements based on what you provide.</p></div><button onClick={downloadResume}>Download draft</button></header><div className="resume-grid"><section className="resume-form"><label>Professional headline<input value={resumeHeadline} onChange={e=>setResumeHeadline(e.target.value)} placeholder="AI & Data Science student | Python | ML projects" /></label><label>Professional summary<textarea value={resumeSummary} onChange={e=>setResumeSummary(e.target.value)} placeholder="Write 2–3 honest lines about your learning focus, projects, and goal…" /></label><label>Skills<input value={resumeSkills} onChange={e=>setResumeSkills(e.target.value)} placeholder="Python, SQL, Machine Learning, React" /></label><button onClick={()=>void generateResumeSuggestions()} disabled={resumeBusy}>{resumeBusy ? 'Reviewing…' : 'Get AI suggestions'}</button>{resumeError && <div className="tutor-error">⚠ {resumeError}</div>}{resumeSuggestions && <pre className="smart-output">{resumeSuggestions}</pre>}</section><article className="resume-preview"><small>LIVE PREVIEW</small><h2>{profile?.name || user.displayName || 'Your name'}</h2><b>{resumeHeadline || 'Your professional headline'}</b><p>{profile?.email || user.email} · {profile?.collegeName || 'College name'}</p><h3>Profile</h3><p>{resumeSummary || 'Write an honest professional summary.'}</p><h3>Skills</h3><p>{resumeSkills || 'Add your technical skills.'}</p><h3>Projects</h3>{state.projects.length ? state.projects.map(project=><p key={project.github}><b>{project.title}</b> · {project.github}</p>) : <p>Add projects in the Projects section.</p>}</article></div></section>}
      {show('reports') && <section className="hub-card"><h2>🚩 Submit a content report</h2><p>Help us identify resources that need attention.</p><input placeholder="Video or lesson URL" value={reportUrl} onChange={e=>setReportUrl(e.target.value)} /><select value={reportReason} onChange={e=>setReportReason(e.target.value)}><option value="">Select issue</option><option>Broken video</option><option>Outdated content</option><option>Incorrect information</option></select><button onClick={()=>void report()}>Submit report</button><h3 className="recent-heading">Your report history</h3>{state.reports.length ? state.reports.map((item,index)=><div className="activity-row" key={`${item.url}-${index}`}><span>#{state.reports.length-index}</span><div><b>{item.reason}</b><small>{item.url}</small></div><em>{item.status || 'Saved locally'}</em></div>) : <div className="empty-state">✓ No content issues reported yet</div>}</section>}
      {show('goals') && <section className="hub-card"><h2>🎯 Weekly goal & notifications</h2><p>This weekend: finish {Math.min(state.goal, 3)} lesson{Math.min(state.goal,3) === 1 ? '' : 's'}, complete one quiz, and practise one program.</p><div className="goal-presets"><button onClick={()=>save({...state,goal:2})}>Light weekend · 2 lessons</button><button onClick={()=>save({...state,goal:4})}>Focused weekend · 4 lessons</button><button onClick={()=>save({...state,goal:6})}>Deep weekend · 6 lessons</button></div><label>{state.goal} lessons per week<input type="range" min="1" max="20" value={state.goal} onChange={e=>save({...state,goal:Number(e.target.value)})} /></label><button onClick={()=>Notification.requestPermission()}>Enable reminders</button></section>}
      {show('languages') && <section className="hub-card"><h2>🌐 Language lessons</h2><select value={state.language} onChange={e=>save({...state,language:e.target.value})}><option>English</option><option>Hindi</option><option>Tamil</option><option>Telugu</option><option>Kannada</option><option>Malayalam</option><option>Marathi</option><option>Bengali</option></select><p>Preferred lesson language: <b>{state.language}</b></p></section>}
      {show('offline') && <section className="hub-card"><h2>📱 Mobile & offline</h2><p>This responsive app can be installed from your browser and its core interface is cached for offline use.</p><button onClick={()=>void installApp()} disabled={!installPrompt}>{installPrompt ? 'Install Engineer Made' : 'Install option available in browser menu'}</button><small>{installPrompt ? 'Install it now for quick mobile access.' : 'Open Chrome menu → Install app if the browser does not show the button yet.'}</small></section>}
      {show('ai-tutor') && <section className="ai-tutor-portal"><header className="tutor-status"><div className="tutor-avatar">🤖</div><div><h2>AI Tutor</h2><span><i /> Online · Gemini</span></div><button title="Clear conversation" onClick={()=>setTutorMessages(tutorMessages.slice(0,1))}>✨ New chat</button></header><div className="tutor-suggestions"><small>TRY ASKING</small><div>{['Explain Newton’s laws with examples','Difference between speed and velocity?','Explain thermodynamics in simple words','Help me choose CSE or ECE','Create a 7-day exam study plan','Explain Ohm’s law in Hinglish'].map(prompt=><button key={prompt} onClick={()=>askTutor(prompt)}>{prompt}</button>)}</div></div><div className="tutor-conversation">{tutorMessages.map((message,index)=><article className={`tutor-message ${message.role}`} key={index}>{message.role==='assistant' && <span className="tutor-avatar">🤖</span>}<div><small>{message.role==='assistant'?'AI TUTOR':'YOU'}</small><p>{message.text}</p>{message.role==='assistant' && <div className="message-actions"><button onClick={()=>speak(message.text)}>🔊 Listen</button><button onClick={()=>navigator.clipboard.writeText(message.text)}>📋 Copy</button></div>}</div></article>)}{tutorBusy && <div className="tutor-typing"><i/><i/><i/> Thinking about your question…</div>}{tutorError && <div className="tutor-error">⚠ {tutorError}</div>}</div><footer className="tutor-composer"><button className={`voice-button ${isListening ? 'is-listening' : ''}`} title="Speak your question" onClick={startVoice}>{isListening ? '🎙️ Listening…' : '🎙️'}</button><textarea aria-label="Ask the AI tutor" placeholder="Type or tap the microphone to speak (English / Hindi / Hinglish)" value={tutorQuestion} onChange={e=>setTutorQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();askTutor();}}}/><button className="send-button" disabled={!tutorQuestion.trim()||tutorBusy} onClick={()=>askTutor()}>Send →</button></footer><small className="tutor-disclaimer">AI can make mistakes. Verify important calculations and safety-critical guidance.</small></section>}
      {show('assessment') && <section className="hub-card"><h2>🧩 Diagnostic skill check</h2><p>Which activity best validates an engineering solution?</p><label className="choice-row"><input type="radio" name="assessment" value="theory" onChange={e=>setAssessmentChoice(e.target.value)} /> Reading theory only</label><label className="choice-row"><input type="radio" name="assessment" value="prototype" onChange={e=>setAssessmentChoice(e.target.value)} /> Building and testing a prototype</label><label className="choice-row"><input type="radio" name="assessment" value="assume" onChange={e=>setAssessmentChoice(e.target.value)} /> Assuming the first design works</label><button onClick={finishAssessment}>Finish assessment</button>{assessmentResult && <div className="result-panel"><b>Your result</b><p>{assessmentResult}</p></div>}{assessmentAttempts.length > 0 && <div className="assessment-history"><b>Recent attempts</b>{assessmentAttempts.slice(0,3).map(attempt=><small key={attempt.id}>{attempt.score}% · {attempt.level} · {new Date(attempt.completedAt).toLocaleDateString()}</small>)}</div>}</section>}
      {show('groups') && <section className="hub-card"><h2>👥 Create a study group</h2><input placeholder="Group name, e.g. GATE Circuit Masters" value={groupName} onChange={e=>setGroupName(e.target.value)} /><select><option>Roadmap learning</option><option>Exam preparation</option><option>Project collaboration</option><option>Interview preparation</option></select><button onClick={()=>{if(groupName.trim()){save({...state,groups:[groupName.trim(),...state.groups]});setGroupName('');}}}>Create group</button>{state.groups.map((group,index)=><div className="activity-row" key={`${group}-${index}`}><span>👥</span><div><b>{group}</b><small>1 member · Invite classmates</small></div><em>Active</em></div>)}</section>}
      {show('simulations') && <section className="hub-card"><h2>⚙️ Ohm’s law circuit simulator</h2><label>Supply voltage: <b>{voltage} V</b><input type="range" min="1" max="24" value={voltage} onChange={e=>setVoltage(Number(e.target.value))} /></label><label>Resistance: <b>{resistance} Ω</b><input type="range" min="1" max="20" value={resistance} onChange={e=>setResistance(Number(e.target.value))} /></label><div className="simulation-output"><span>Calculated current</span><strong>{(voltage/resistance).toFixed(2)} A</strong><small>I = V ÷ R</small></div><div className="circuit-line"><i style={{opacity:Math.min(1,(voltage/resistance)/3)}} />🔋───💡───</div></section>}
      {show('interviews') && <section className="hub-card"><h2>🎙️ Technical mock interview</h2><div className="question-box"><small>QUESTION 1 · PROBLEM SOLVING</small><h3>Tell me about an engineering problem you solved and how you validated the result.</h3></div><textarea placeholder="Structure your response using Situation, Task, Action and Result…" value={interviewAnswer} onChange={e=>setInterviewAnswer(e.target.value)} /><div className="interview-score"><span>Structure {interviewAnswer.length > 120 ? '✓' : '○'}</span><span>Technical detail {interviewAnswer.length > 240 ? '✓' : '○'}</span><span>Result {/result|improved|reduced|increased/i.test(interviewAnswer) ? '✓' : '○'}</span></div><button onClick={()=>setInterviewAnswer(interviewAnswer)}>Save practice answer</button></section>}
      {show('placement') && <section className="hub-card"><h2>🔒 Placement Preparation</h2><p>This feature is coming soon. It will contain verified, role-specific preparation tasks rather than an artificial readiness score.</p><span className="badge">COMING SOON</span></section>}
      {show('repo-analysis') && <section className="hub-card"><h2>🔎 Real GitHub portfolio review</h2><p>Analyzes public GitHub repository metadata and README availability through the GitHub API.</p><input placeholder="https://github.com/username/project" value={repoUrl} onChange={e=>setRepoUrl(e.target.value)} /><button onClick={()=>void analyseRepository()} disabled={repoBusy || !repoUrl.trim()}>{repoBusy ? 'Analyzing GitHub…' : 'Analyze repository'}</button>{repoResult && <div className="tutor-error">⚠ {repoResult}</div>}{repoRubric && <div className="result-panel"><b>{repoRubric.repository.fullName} · {repoRubric.portfolioScore}% portfolio score</b><p>{repoRubric.repository.description}</p><small>{repoRubric.repository.language} · {repoRubric.repository.stars} stars · README {repoRubric.repository.readmePresent ? 'found' : 'missing'}</small><div className="quality-bars">{repoRubric.rubric.map((item:any)=><span key={item.label}>{item.label} <b>{item.score}%</b><i style={{width:`${item.score}%`}} /><small>{item.tip}</small></span>)}</div></div>}</section>}
      {show('analytics') && <section className="hub-card"><h2>📈 Your learning intelligence</h2><div className="analytics-score"><div><strong>{Math.min(100,completedLessons.length*4+20)}</strong><span>Readiness score</span></div><p>Your score combines completed lessons, assessments, projects and placement activity.</p></div><div className="completion-chart" aria-label="Learner completion chart">{Array.from({length:7},(_,index)=>Math.min(100, Math.max(8, completedLessons.length * (index + 1) * 3))).map((value,index)=><div key={index}><i style={{height:`${value}%`}} /><small>{['M','T','W','T','F','S','S'][index]}</small></div>)}</div>{[['Learning progress',Math.min(100,completedLessons.length*5)],['Assessment strength',assessmentAttempts[0]?.score || state.quizScore],['Portfolio readiness',Math.min(100,state.projects.length*25)],['Placement preparation',Math.round(state.placementTasks.length/6*100)]].map(([label,value])=><div className="analytics-row" key={String(label)}><span>{label}</span><b>{value}%</b><div className="progress-track"><i style={{width:`${value}%`}} /></div></div>)}</section>}
      {show('skill-tree') && <section className="hub-card hub-wide"><h2>🌳 {profile?.careerPathId ? 'Your role skill tree' : 'Engineering skill tree'}</h2><p>Skills unlock in order as you progress through your selected roadmap.</p><div className="skill-tree">{['Foundations','Core concepts','Applied practice','Portfolio project','Interview ready'].map((skill,index)=>{const unlocked=completedLessons.length >= index*3; return <article key={skill} className={unlocked ? 'unlocked' : ''}><span>{unlocked ? '✓' : '🔒'}</span><b>{skill}</b><small>{unlocked ? 'Unlocked' : `Complete ${index*3} lessons`}</small></article>;})}</div></section>}
      {show('adaptive-practice') && <section className="hub-card"><h2>🎯 Adaptive practice</h2><p>Your task: before shipping an engineering solution, what should you do first?</p><label className="choice-row"><input type="radio" name="adaptive" onChange={()=>setPracticeChoice('validate')} /> Define a measurable validation test</label><label className="choice-row"><input type="radio" name="adaptive" onChange={()=>setPracticeChoice('measure')} /> Ask for general feedback only</label><label className="choice-row"><input type="radio" name="adaptive" onChange={()=>setPracticeChoice('guess')} /> Assume it works after implementation</label><button onClick={()=>void runAdaptivePractice()}>Check and adapt</button>{practiceResult && <div className="result-panel"><b>Mistake analysis</b><p>{practiceResult}</p></div>}</section>}
      {show('weakness-heatmap') && <section className="hub-card"><h2>🗺️ Roadmap weakness heatmap</h2><p>Choose a focus area below to open the matching practice tool.</p><div className="heatmap-grid">{[['Core concepts',completedLessons.length >= 3 ? 'strong' : 'focus','quiz'],['Applied practice',assessmentAttempts.length ? 'steady' : 'focus','adaptive-practice'],['Portfolio evidence',state.projects.length ? 'steady' : 'focus','projects'],['Interview communication',interviewAnswer.length > 120 ? 'strong' : 'focus','interviews']].map(([skill,status,target])=><article className={String(status)} key={String(skill)}><b>{skill}</b><span>{status === 'focus' ? 'Focus next' : status === 'steady' ? 'Building' : 'Strong'}</span><button onClick={()=>onFeatureChange?.(String(target))}>Open focus →</button></article>)}</div></section>}
      {show('daily-challenge') && <section className="daily-challenge-board"><header><div><span>🎯</span><h2>Daily challenges</h2></div><p>Complete today’s role-relevant tasks to earn XP · Progress: {dailyTasks.filter(task => state.completedChallenges.includes(task.id)).length}/3</p></header><div className="daily-task-list">{dailyTasks.map(task => { const done = state.completedChallenges.includes(task.id); return <article className={done ? 'done' : ''} key={task.id}><span className="daily-task-icon">{done ? '✓' : task.icon}</span><div><b>{task.title}</b><small>+{task.xp} XP</small></div><button className="daily-go" onClick={() => onFeatureChange?.(task.target)} disabled={!onFeatureChange}>Go</button><button className="daily-complete" onClick={() => void completeChallenge(task.id)} disabled={done}>{done ? 'Completed ✓' : 'Mark done'}</button></article>; })}</div>{dailyError && <div className="tutor-error">⚠ {dailyError}</div>}<footer><span>⚡ {dailyStatus?.streak ? `${dailyStatus.streak}-day saved streak · ` : ''}Keep a short daily learning streak—consistency builds real engineering skill.</span><b>{dailyStatus?.xp ?? dailyTasks.filter(task => state.completedChallenges.includes(task.id)).reduce((sum, task) => sum + task.xp, 0)} XP today</b></footer></section>}
      {show('ai-summarizer') && <section className="hub-card hub-wide"><h2>🧾 AI engineering summarizer</h2><textarea value={smartTopic} onChange={e=>setSmartTopic(e.target.value)} placeholder="Paste notes, a documentation section, or a concept to summarize…" /><button onClick={()=>void generateStudyAsset('summary')} disabled={smartBusy || !smartTopic.trim()}>{smartBusy ? 'Creating summary…' : 'Summarize for revision'}</button>{smartResult && <pre className="smart-output">{smartResult}</pre>}{tutorError && <div className="tutor-error">⚠ {tutorError}</div>}</section>}
      {show('cheatsheet') && <section className="hub-card hub-wide"><h2>🗒️ Cheatsheet generator</h2><input value={smartTopic} onChange={e=>setSmartTopic(e.target.value)} placeholder="Example: REST API authentication, Ohm’s law, SQL joins" /><button onClick={()=>void generateStudyAsset('cheatsheet')} disabled={smartBusy || !smartTopic.trim()}>{smartBusy ? 'Creating cheatsheet…' : 'Generate cheatsheet'}</button>{smartResult && <pre className="smart-output">{smartResult}</pre>}{tutorError && <div className="tutor-error">⚠ {tutorError}</div>}</section>}
      {show('career-explorer') && <section className="hub-card hub-wide"><h2>🧭 Career explorer</h2><h3>{profile?.careerPathId ? 'Your selected engineering role' : 'Choose a role to personalize this view'}</h3><p>Build evidence in four areas: technical foundations, applied projects, communication, and a professional GitHub/portfolio presence.</p><div className="career-points"><article><b>Learn</b><span>Finish core modules in your roadmap</span></article><article><b>Build</b><span>Create two role-relevant projects</span></article><article><b>Show</b><span>Document work on GitHub and your resume</span></article><article><b>Practise</b><span>Complete mock interviews and placement tasks</span></article></div><Link className="hub-link" to="/profile">Review or change selected role →</Link></section>}
      {show('job-readiness') && <section className="hub-card"><h2>📐 Job readiness predictor</h2>{(()=>{const lessons=Math.min(100,completedLessons.length*10); const assessment=assessmentAttempts[0]?.score || state.quizScore; const portfolio=Math.min(100,state.projects.length*50); const placement=Math.round(state.placementTasks.length/6*100); const score=Math.round((lessons+assessment+portfolio+placement)/4); return <><strong className="big-number">{score}%</strong><p>Transparent estimate from learning, assessment, portfolio and placement signals.</p>{[['Lessons',lessons],['Assessment',assessment],['Portfolio',portfolio],['Placement',placement]].map(([label,value])=><div className="analytics-row" key={String(label)}><span>{label}</span><b>{value}%</b><div className="progress-track"><i style={{width:`${value}%`}} /></div></div>)}</>;})()}</section>}
      {show('doubt-upload') && <section className="hub-card hub-wide"><h2>📷 AI code, diagram & circuit doubts</h2><p>Attach an image or PDF and describe the issue. Gemini Vision analyzes the reference in memory; it is not stored publicly.</p><div className="doubt-grid"><label>Doubt type<select value={doubtKind} onChange={e=>setDoubtKind(e.target.value)}><option>Code issue</option><option>Circuit diagram</option><option>Engineering drawing</option><option>Maths / calculation</option><option>Project design</option></select></label><label>Reference file (optional)<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" onChange={e=>selectDoubtReference(e.target.files?.[0])} /><small>{doubtFileName || 'Nothing attached'}</small></label></div>{doubtPreview && <img className="doubt-preview" src={doubtPreview} alt="Local doubt reference preview" />}<textarea value={doubtDescription} onChange={e=>setDoubtDescription(e.target.value)} placeholder="What did you expect? What actually happened? Include values, error text, circuit components, or constraints…" /><button onClick={()=>void askDoubtTutor()} disabled={doubtBusy || !doubtDescription.trim()}>{doubtBusy ? 'Reviewing your doubt…' : doubtFile ? 'Analyze with Gemini Vision' : 'Ask engineering tutor'}</button>{doubtResult && <pre className="smart-output">{doubtResult}</pre>}</section>}
    </div>{details && activeFeature !== 'ai-tutor' && <aside className="feature-guide"><section><span className="dashboard-kicker">HOW IT WORKS</span><h2>Get the best result</h2><ol>{details.steps.map(step=><li key={step}>{step}</li>)}</ol></section><section className="feature-tip"><b>💡 Engineer’s tip</b><p>{details.tip}</p></section><section><span className="dashboard-kicker">YOUR DATA</span><p className="privacy-note">Your activity in this local version is stored only in this browser.</p></section></aside>}</div>
  </div>;
}
