import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import axios from 'axios';

const API = process.env.REACT_APP_API_URL || (process.env.NODE_ENV === 'production' ? '' : 'http://localhost:8000');
type TutorChatMessage = { role: 'user' | 'assistant'; text: string };
let pyodideReady: Promise<any> | null = null;

type SavedState = {
  bookmarks: string[]; notes: { text: string; date: string }[];
  projects: { title: string; github: string }[];
  reports: { url: string; reason: string; status?: string }[]; goal: number; language: string;
  quizScore: number; codePassed: boolean; groups: string[]; placementTasks: string[]; completedChallenges: string[]; challengeDate?: string; flashcardsKnown: string[];
  schedule?: { frequency: 'daily' | 'weekly'; time: string; enabled: boolean };
  focusMinutes: number; focusSessions: { minutes: number; subject: string; completedAt: string }[]; doubts: { text: string; createdAt: string }[];
};

const initial: SavedState = { bookmarks: [], notes: [], projects: [], reports: [], goal: 5, language: 'English', quizScore: 0, codePassed: false, groups: [], placementTasks: [], completedChallenges: [], flashcardsKnown: [], focusMinutes: 0, focusSessions: [], doubts: [] };

const featureInfo: Record<string, { icon: string; title: string; description: string; metrics: [string,string][]; steps: string[]; tip: string }> = {
  recommendation: { icon:'✨', title:'Personalized Recommendations', description:'A learning plan tailored to your education level, college profile and completed lessons.', metrics:[['Learning level','Personalized'],['Plan type','Adaptive'],['Next review','After 3 lessons']], steps:['Review your suggested focus','Open the recommended roadmap','Complete lessons to improve future suggestions'], tip:'Keep your profile and progress updated for more accurate recommendations.' },
  continue: { icon:'▶', title:'Continue Learning', description:'Resume lessons exactly where you stopped and review your recent learning activity.', metrics:[['Recent lessons','Synced locally'],['Progress','Auto tracked'],['History','Last viewed']], steps:['Select a recent lesson','Continue the video or tutorial','Mark it complete when finished'], tip:'Short daily learning sessions are easier to maintain than occasional long sessions.' },
  quiz: { icon:'🧠', title:'Module Quizzes', description:'Check your understanding with short assessments and immediate feedback.', metrics:[['Current score','Live'],['Attempts','Unlimited'],['Feedback','Instant']], steps:['Read the question carefully','Select the best answer','Check the explanation and retry'], tip:'Review the lesson before retrying a question you missed.' },
  flashcards: { icon:'🗂️', title:'Flashcards', description:'Use focused recall cards separately from quizzes and track the concepts you already know.', metrics:[['Mode','Active recall'],['Deck','Role focused'],['Progress','Saved']], steps:['Read the prompt before flipping','Explain the answer in your own words','Mark the card known or review it again'], tip:'Flashcards work best in short, repeated sessions.' },
  'focus-timer': { icon:'🍅', title:'Focus Timer', description:'Run a real study session timer and save completed minutes in this browser.', metrics:[['Method','Pomodoro'],['Tracking','Local'],['Sessions','Real time']], steps:['Choose a session length','Name the task you are studying','Start and complete the timer'], tip:'Use a single clearly named task for each focus session.' },
  'focus-music': { icon:'🎵', title:'Focus Music', description:'Open a chosen focus soundtrack in YouTube. Playback is supplied by YouTube, not simulated.', metrics:[['Source','YouTube'],['Control','Your browser'],['Storage','None']], steps:['Choose a soundtrack','Open it in a new tab','Control playback directly on YouTube'], tip:'Keep music low enough that it does not compete with reading.' },
  'doubt-forum': { icon:'👥', title:'Doubt Forum', description:'Capture a clear technical doubt and open it in the AI tutor. Public peer posting requires a moderated backend.', metrics:[['Posts','Your saved doubts'],['Privacy','This browser'],['Help','AI tutor']], steps:['Write the exact doubt','Include expected and actual behaviour','Open the tutor with the context'], tip:'Specific inputs, error messages and expected outputs produce better answers.' },
  'refer-friends': { icon:'🤝', title:'Refer Friends', description:'Share an actual sign-up link; copied and shared links are generated from your account ID.', metrics:[['Link','Personalised'],['Sharing','Browser'],['Rewards','None claimed']], steps:['Copy or share your personal link','Send it only to people who want it','Do not claim referral rewards until server tracking exists'], tip:'Keep referral messages short and honest about the platform.' },
  themes: { icon:'🌈', title:'Themes', description:'Choose an interface colour theme stored on this device.', metrics:[['Themes','4'],['Apply','Instant'],['Storage','This browser']], steps:['Choose a theme','Check contrast before using it','Switch back any time'], tip:'Choose the theme with the clearest text contrast for long study sessions.' },
  'my-story': { icon:'🤖', title:'My Story', description:'Generate a factual learning summary from your saved lesson, assessment and project activity.', metrics:[['Source','Your activity'],['Claims','No invented data'],['Format','Copyable']], steps:['Complete real activity first','Generate your summary','Use it as a reflection, not a resume claim'], tip:'A useful story names what you did, not achievements you did not earn.' },
  wallpapers: { icon:'🖼️', title:'Wallpapers', description:'Create a simple study wallpaper with your own focus message and download it as a PNG.', metrics:[['Text','Your message'],['Export','PNG'],['Storage','Download']], steps:['Write a personal study reminder','Generate the wallpaper','Download it for your device'], tip:'Short messages work best as wallpapers.' },
  performance: { icon:'📈', title:'Performance', description:'View your actual assessment history and focus minutes, with no fabricated score trend.', metrics:[['Assessments','Recorded'],['Focus','Timer sessions'],['Trend','Your data']], steps:['Complete assessments','Run focus sessions','Review the chart after several attempts'], tip:'One result is not a trend—review several attempts.' },
  badges: { icon:'🏅', title:'Badges', description:'See milestones unlocked only by your recorded learning activity.', metrics:[['Rules','Visible'],['Claims','Activity based'],['Export','Not issued']], steps:['Complete the listed requirement','Return to check unlocks','Use certificates only when server-issued'], tip:'Badges are motivation, not evidence of a qualification.' },
  'loot-box': { icon:'🎁', title:'Study Prompt Box', description:'Draw a practical next-study prompt. It does not award fake XP, money or rewards.', metrics:[['Prompts','Actionable'],['Rewards','None claimed'],['Storage','None']], steps:['Draw one prompt','Complete the action','Return only when you are ready for another'], tip:'Treat the prompt as a small next action, not a random reward.' },
  whiteboard: { icon:'🎨', title:'Whiteboard', description:'Draw diagrams or work through a problem directly in your browser and export a PNG.', metrics:[['Canvas','Interactive'],['Export','PNG'],['Storage','Download']], steps:['Choose a colour and pen size','Draw your diagram','Save it as a PNG'], tip:'Label diagrams with values and units before exporting.' },
  coding: { icon:'💻', title:'Coding Practice', description:'Write and run Python or JavaScript directly in your browser.', metrics:[['Languages','Python, JavaScript'],['Execution','Browser-only'],['Input','Supported']], steps:['Choose Python or JavaScript','Write code and optional standard input','Run it and inspect the output'], tip:'Test small inputs first, then add edge cases.' },
  projects: { icon:'🚀', title:'Engineering Projects', description:'Build a verified portfolio by submitting engineering projects hosted on GitHub.', metrics:[['Submitted','Saved locally'],['Repository','GitHub'],['Portfolio','Ready']], steps:['Create a clear project repository','Add a useful README and screenshots','Submit its title and GitHub URL'], tip:'A strong README should explain the problem, solution, setup and results.' },
  certificates: { icon:'🏆', title:'Certificates & Achievements', description:'Track learning milestones, unlock badges and print completion evidence.', metrics:[['Lessons', 'Progress based'],['Current badge','Rising Engineer'],['Certificate','Printable']], steps:['Complete roadmap lessons','Reach the required milestone','Print or save your certificate'], tip:'Complete one full roadmap to create a stronger achievement story.' },
  bookmarks: { icon:'🔖', title:'Saved Resources', description:'Keep important lessons, references and tutorials in one personal collection.', metrics:[['Storage','Local'],['Collection','Personal'],['Access','Instant']], steps:['Save a useful resource','Return to it from this page','Remove items after completing them'], tip:'Bookmark only high-value references so your collection stays useful.' },
  notes: { icon:'📝', title:'Learning Notes', description:'Capture concepts, formulas, questions and revision points while studying.', metrics:[['Notes','Auto saved'],['Privacy','On device'],['Format','Quick notes']], steps:['Write one clear idea per note','Include a question or example','Review notes before quizzes'], tip:'Writing a concept in your own words improves long-term recall.' },
  resume: { icon:'📄', title:'AI-Assisted Resume Builder', description:'Write your own resume while receiving targeted AI suggestions and a live preview.', metrics:[['Author','You'],['Guidance','AI suggestions'],['Preview','Live']], steps:['Add your headline, summary and skills','Generate improvement suggestions','Review the preview and download your draft'], tip:'Use evidence and measurable results instead of generic adjectives.' },
  reports: { icon:'🚩', title:'Content Quality Reports', description:'Report broken, outdated or incorrect course content so learning material stays reliable.', metrics:[['Report types','3'],['Saved reports','Local history'],['Review status','Tracked']], steps:['Paste the exact lesson or video URL','Choose the most accurate issue','Submit and retain the report record'], tip:'Add the exact affected resource URL so the issue can be reproduced quickly.' },
  goals: { icon:'🎯', title:'Weekly Goals & Notifications', description:'Set a realistic weekly lesson target and enable reminders to remain consistent.', metrics:[['Target','Adjustable'],['Frequency','Weekly'],['Reminder','Browser']], steps:['Choose lessons per week','Enable browser reminders','Review progress at week end'], tip:'A sustainable goal you meet every week is better than an ambitious one you abandon.' },
  schedule: { icon:'⏰', title:'Schedule Task', description:'Set a daily or weekly learning summary. Email delivery is enabled only after the server mail provider is configured.', metrics:[['Cadence','Daily or weekly'],['Destination','Signed-in email'],['Status','Config required']], steps:['Choose a frequency and time','Save the schedule','Connect the server email provider before relying on delivery'], tip:'Use browser reminders immediately; email needs an approved server-side mail provider.' },
  languages: { icon:'🌐', title:'Regional Language Learning', description:'Choose your preferred lesson language for a more comfortable learning experience.', metrics:[['Languages','8'],['Preference','Saved'],['Content','Expanding']], steps:['Select your preferred language','Use translated lesson resources','Change language whenever needed'], tip:'Technical terms may remain in English to keep them industry-relevant.' },
  'ai-tutor': { icon:'🤖', title:'AI Engineering Tutor', description:'Ask technical questions and receive guided explanations, examples and suggested next steps.', metrics:[['Subjects','All engineering'],['Mode','Guided learning'],['Availability','Local demo']], steps:['Enter a focused technical question','Review the explanation and example','Ask a follow-up or open the related roadmap'], tip:'Include the subject, current level and exact point of confusion in your question.' },
  assessment: { icon:'🧩', title:'Adaptive Skill Assessments', description:'Measure current skills and receive a recommended learning level based on your answers.', metrics:[['Questions','Adaptive'],['Result','Instant'],['Plan','Skill based']], steps:['Choose an answer to each question','Submit your assessment','Use the result to select your next roadmap'], tip:'Answer honestly—the result is useful only when it reflects your current ability.' },
  groups: { icon:'👥', title:'Collaborative Study Groups', description:'Create or join focused peer groups for roadmaps, projects and exam preparation.', metrics:[['Group size','2–8 learners'],['Activity','Collaborative'],['Storage','Local demo']], steps:['Name the study group','Choose a common learning goal','Create the group and invite classmates'], tip:'Groups work best with a fixed weekly meeting and a shared goal.' },
  simulations: { icon:'⚙️', title:'Engineering Simulations', description:'Explore circuit and mechanical behaviour by changing inputs and observing calculated outputs.', metrics:[['Labs','Circuit & mechanics'],['Inputs','Interactive'],['Results','Live']], steps:['Choose a simulation','Adjust the input controls','Compare the calculated result with your prediction'], tip:'Predict the output before moving a control to strengthen engineering intuition.' },
  interviews: { icon:'🎙️', title:'Mock Interviews', description:'Practise technical and behavioural interview questions with structured self-evaluation.', metrics:[['Question bank','Mixed'],['Timer','Practice'],['Feedback','Checklist']], steps:['Read the interview question','Prepare and record your response notes','Compare it against the answer checklist'], tip:'Use the STAR structure for behavioural questions: Situation, Task, Action, Result.' },
  placement: { icon:'🎓', title:'Placement Preparation', description:'Track the essential tasks required for campus placements and graduate hiring.', metrics:[['Checklist','6 stages'],['Progress','Tracked'],['Focus','Job readiness']], steps:['Complete profile and resume tasks','Practise aptitude and technical topics','Finish mock interviews before applying'], tip:'Treat placement preparation as a weekly routine, not a last-minute activity.' },
  'repo-analysis': { icon:'🔎', title:'GitHub Repository Analysis', description:'Review repository quality using practical portfolio-readiness checks.', metrics:[['Checks','README & structure'],['Input','GitHub URL'],['Result','Instant review']], steps:['Paste a public GitHub repository URL','Run the portfolio readiness check','Fix the suggested repository improvements'], tip:'Recruiters should understand the project’s value within the first minute.' },
  leaderboard: { icon:'🥇', title:'College Leaderboards', description:'Compare learning activity through points earned from lessons, quizzes and projects.', metrics:[['Ranking','Weekly'],['Points','Activity based'],['Scope','College']], steps:['Complete lessons and quizzes','Submit portfolio projects','Return weekly to review ranking'], tip:'Use rankings for motivation, but measure success by skills gained.' },
  analytics: { icon:'📈', title:'Advanced Learning Analytics', description:'Understand progress, consistency, assessment performance and portfolio readiness.', metrics:[['Progress','Real-time'],['Insights','Multi-signal'],['Audience','Learner & admin']], steps:['Review your activity summary','Identify the weakest learning signal','Choose one improvement action for this week'], tip:'Track trends over several weeks instead of reacting to one day of activity.' },
  'skill-tree': { icon:'🌳', title:'Engineering Skill Tree', description:'See the skills you unlock as you complete your selected engineering roadmap.', metrics:[['Track','Role focused'],['Progress','Live'],['Milestones','Unlocked']], steps:['Complete lessons in your selected track','Unlock the next skill milestone','Use locked skills to plan your next study session'], tip:'Build foundations before jumping to advanced tools or projects.' },
  'adaptive-practice': { icon:'🎯', title:'Adaptive Practice & Mistake Analysis', description:'Practise an engineering decision, receive immediate feedback, and focus the next attempt on the weak area.', metrics:[['Difficulty','Adaptive'],['Feedback','Instant'],['Focus','Weak skills']], steps:['Answer the scenario','Review the feedback','Use the recommended revision action'], tip:'Do not only retry a question—understand which engineering principle caused the mistake.' },
  'weakness-heatmap': { icon:'🗺️', title:'Weakness Heatmap', description:'A clear map of the skills that need attention based on your learning, assessment and portfolio signals.', metrics:[['Signals','4'],['Scope','Your roadmap'],['Action','Focused']], steps:['Review the red and amber skills','Open one weak skill for revision','Retake practice after studying'], tip:'Choose one weak skill at a time; focused improvement beats scattered revision.' },
  'daily-challenge': { icon:'⚡', title:'Daily Engineering Challenge', description:'Complete one small, role-relevant task every day to keep your learning momentum active.', metrics:[['Frequency','Daily'],['Time','15 minutes'],['Reward','Momentum']], steps:['Read today’s challenge','Complete it before moving on','Return tomorrow for a new challenge'], tip:'Consistency is more valuable than waiting for the perfect long study session.' },
  'ai-summarizer': { icon:'🧾', title:'AI Engineering Summarizer', description:'Turn technical notes, documentation or lesson text into concise revision points.', metrics:[['Input','Your text'],['Output','Revision notes'],['Mode','AI assisted']], steps:['Paste the concept or notes','Ask for a clear summary','Save useful points in Learning Notes'], tip:'Provide the source context and the target level for more useful summaries.' },
  cheatsheet: { icon:'🗒️', title:'Engineering Cheatsheet Generator', description:'Generate a compact revision checklist for a topic in your selected engineering role.', metrics:[['Format','Quick revision'],['Topic','Your choice'],['Output','Copyable']], steps:['Enter one focused topic','Generate a concise cheatsheet','Review it before practice or interviews'], tip:'Use cheatsheets for recall, then return to the full lesson for deep understanding.' },
  'career-explorer': { icon:'🧭', title:'Engineering Career Explorer', description:'Understand the skills, portfolio evidence and entry-level direction for your selected engineering role.', metrics:[['Role','Selected roadmap'],['Focus','Career-ready'],['Next step','Projects']], steps:['Review your selected role','Compare the readiness areas','Choose one skill or project to build next'], tip:'A role becomes credible when you can show projects, not only course completion.' },
  'job-readiness': { icon:'📐', title:'Job Readiness Predictor', description:'A transparent readiness estimate based on your completed lessons, assessment attempts, projects and placement tasks.', metrics:[['Model','Transparent'],['Signals','4'],['Action','Next best step']], steps:['Review the readiness signals','Improve the lowest signal','Recheck after completing meaningful work'], tip:'This is a preparation indicator, not a prediction of hiring outcomes.' },
  'doubt-upload': { icon:'📷', title:'Code, Diagram & Circuit Doubts', description:'Attach a reference locally, explain exactly where you are stuck, and get a structured engineering explanation from the AI tutor.', metrics:[['Formats','Image, PDF, code'],['Input','Private session'],['Help','Guided']], steps:['Attach a relevant reference','Describe the expected and actual result','Ask for a step-by-step explanation'], tip:'A clear description of inputs, expected output and error message produces the strongest technical help.' },
};

export default function LearningHub({ embedded = false, activeFeature, onFeatureChange }: { embedded?: boolean; activeFeature?: string; onFeatureChange?: (feature: string) => void }) {
  const { user, loading, profile, completedLessons, bookmarks, saveBookmark, removeBookmark, assessmentAttempts, recordAssessment } = useAuth();
  const storageKey = `engineer-made-hub:${user?.uid || 'guest'}`;
  const [state, setState] = useState<SavedState>(() => {
    const today = new Date().toISOString().slice(0, 10);
    try {
      const saved = { ...initial, ...JSON.parse(localStorage.getItem(storageKey) || '{}') } as SavedState;
      const normalized = { ...saved, focusMinutes: Number(saved.focusMinutes || 0), focusSessions: Array.isArray(saved.focusSessions) ? saved.focusSessions : [], doubts: Array.isArray(saved.doubts) ? saved.doubts : [] };
      return normalized.challengeDate === today ? normalized : { ...normalized, completedChallenges: [], challengeDate: today };
    } catch { return { ...initial, challengeDate: today }; }
  });
  const [note, setNote] = useState('');
  const [projectTitle, setProjectTitle] = useState(''); const [github, setGithub] = useState(''); const [projectError, setProjectError] = useState('');
  const [reportUrl, setReportUrl] = useState(''); const [reportReason, setReportReason] = useState('');
  const [codeLanguage, setCodeLanguage] = useState<'python' | 'javascript'>('python'); const [code, setCode] = useState('print("Hello Engineer")'); const [codeInput, setCodeInput] = useState(''); const [codeOutput, setCodeOutput] = useState('Ready to run in your browser.'); const [codeBusy, setCodeBusy] = useState(false);
  const [isListening, setIsListening] = useState(false); const [openedNote, setOpenedNote] = useState<{ text:string; date:string } | null>(null);
  const [quizChoice, setQuizChoice] = useState('');
  const [flashcardIndex, setFlashcardIndex] = useState(0); const [flashcardFlipped, setFlashcardFlipped] = useState(false);
  const [bookmarkTitle, setBookmarkTitle] = useState(''); const [bookmarkUrl, setBookmarkUrl] = useState(''); const [bookmarkError, setBookmarkError] = useState('');
  const [timerPreset, setTimerPreset] = useState(25); const [timerSeconds, setTimerSeconds] = useState(25 * 60); const [timerRunning, setTimerRunning] = useState(false); const [focusSubject, setFocusSubject] = useState('');
  const [doubtText, setDoubtText] = useState(''); const [story, setStory] = useState(''); const [wallpaperText, setWallpaperText] = useState('Build your next skill today.'); const [studyPrompt, setStudyPrompt] = useState('');
  const [theme, setTheme] = useState(() => localStorage.getItem('engineer-made-theme') || 'royal'); const canvasRef = useRef<HTMLCanvasElement | null>(null); const drawing = useRef(false); const [penColor, setPenColor] = useState('#f0c95b'); const [penSize, setPenSize] = useState(4);
  const [tutorQuestion, setTutorQuestion] = useState('');
  const [tutorMessages, setTutorMessages] = useState<TutorChatMessage[]>([{role:'assistant',text:'Namaste! 👋 I’m your AI Engineering Tutor. Ask me about engineering concepts, exam preparation, projects, careers, or college guidance. You can type or use the microphone in English, Hindi, or Hinglish.'}]);
  const [tutorBusy, setTutorBusy] = useState(false); const [tutorError, setTutorError] = useState('');
  const [assessmentChoice, setAssessmentChoice] = useState(''); const [assessmentResult, setAssessmentResult] = useState(''); const [assessmentStep, setAssessmentStep] = useState(0); const [assessmentAnswers, setAssessmentAnswers] = useState<string[]>([]);
  const [certificateCode, setCertificateCode] = useState(''); const [certificateError, setCertificateError] = useState(''); const [issuingCertificate, setIssuingCertificate] = useState(false);
  const [groupName, setGroupName] = useState(''); const [voltage, setVoltage] = useState(12); const [resistance, setResistance] = useState(6); const [simulation, setSimulation] = useState<'circuit'|'power'|'beam'>('circuit'); const [simulationLoad, setSimulationLoad] = useState(40);
  const [interviewAnswer, setInterviewAnswer] = useState(''); const [repoUrl, setRepoUrl] = useState(''); const [repoResult, setRepoResult] = useState(''); const [repoRubric, setRepoRubric] = useState<any>(null); const [repoBusy, setRepoBusy] = useState(false);
  const [practiceChoice, setPracticeChoice] = useState(''); const [practiceResult, setPracticeResult] = useState(''); const [dailyFocus, setDailyFocus] = useState('');
  const [smartTopic, setSmartTopic] = useState(''); const [smartResult, setSmartResult] = useState(''); const [smartBusy, setSmartBusy] = useState(false);
  const [doubtKind, setDoubtKind] = useState('Code issue'); const [doubtDescription, setDoubtDescription] = useState(''); const [doubtFileName, setDoubtFileName] = useState(''); const [doubtFile, setDoubtFile] = useState<File | null>(null); const [doubtPreview, setDoubtPreview] = useState(''); const [doubtResult, setDoubtResult] = useState(''); const [doubtBusy, setDoubtBusy] = useState(false);
  const [resumeHeadline, setResumeHeadline] = useState(''); const [resumeSummary, setResumeSummary] = useState(''); const [resumeSkills, setResumeSkills] = useState(''); const [resumeSuggestions, setResumeSuggestions] = useState(''); const [resumeBusy, setResumeBusy] = useState(false); const [resumeError, setResumeError] = useState('');
  const [dailyStatus, setDailyStatus] = useState<{ xp: number; streak: number } | null>(null); const [dailyError, setDailyError] = useState('');
  const history = useMemo(() => { try { return JSON.parse(localStorage.getItem('engineer-made-history') || '[]'); } catch { return []; } }, []);
  const save = (next: SavedState) => { setState(next); localStorage.setItem(storageKey, JSON.stringify(next)); };
  const recommendation = profile?.educationStatus === 'Graduated' ? 'Industry-ready projects and interview preparation' : profile?.educationStatus === 'PG' ? 'Advanced specialization and research projects' : 'Foundation-first roadmap with guided projects';
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('engineer-made-theme', theme); }, [theme]);
  useEffect(() => {
    if (!timerRunning) return;
    const interval = window.setInterval(() => setTimerSeconds(current => {
      if (current > 1) return current - 1;
      window.clearInterval(interval); setTimerRunning(false);
      save({ ...state, focusMinutes: state.focusMinutes + timerPreset, focusSessions: [{ minutes: timerPreset, subject: focusSubject.trim() || 'Untitled focus session', completedAt: new Date().toISOString() }, ...state.focusSessions].slice(0, 50) });
      return 0;
    }), 1000);
    return () => window.clearInterval(interval);
  }, [timerRunning, timerPreset, focusSubject, state]);

  if (loading) return <div className="loading"><div className="spinner" /></div>;
  if (!user) return <Navigate to="/login" replace />;

  const addNote = () => { if (!note.trim()) return; save({ ...state, notes: [{ text: note.trim(), date: new Date().toLocaleDateString() }, ...state.notes] }); setNote(''); };
  const addProject = () => {
    const repositoryUrl = github.trim();
    if (!projectTitle.trim()) { setProjectError('Enter a project title.'); return; }
    if (!/^https:\/\/(?:www\.)?github\.com\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+(?:\.git)?\/?$/i.test(repositoryUrl)) { setProjectError('Enter a valid GitHub repository URL.'); return; }
    save({ ...state, projects: [{ title: projectTitle.trim(), github: repositoryUrl }, ...state.projects] }); setProjectTitle(''); setGithub(''); setProjectError('');
  };
  const report = async () => {
    if (!reportUrl || !reportReason) return;
    try {
      const token = await user.getIdToken();
      await axios.post(`${API}/api/reports`, { resourceUrl: reportUrl, issueType: reportReason.toLowerCase().replace(/\s+/g, '_') }, { headers: { Authorization: `Bearer ${token}` } });
      save({ ...state, reports: [{ url: reportUrl, reason: reportReason, status: 'Submitted for review' }, ...state.reports] });
      setReportUrl(''); setReportReason('');
    } catch (error: any) { setTutorError(error?.response?.data?.detail || 'The report could not be submitted. Please retry.'); }
  };
  const codeTemplates = { python:'print("Hello Engineer")', javascript:'console.log("Hello Engineer");' };
  const changeCodeLanguage = (language: 'python' | 'javascript') => { setCodeLanguage(language); setCode(codeTemplates[language]); setCodeOutput('Ready to run in your browser.'); };
  const runCode = async () => {
    if (!code.trim() || codeBusy) return;
    setCodeBusy(true); setCodeOutput(codeLanguage === 'python' ? 'Loading the free Python runtime…' : 'Running JavaScript…');
    try {
      if (codeLanguage === 'javascript') {
        const output:string[] = [];
        const write = (...items:any[]) => output.push(items.map(String).join(' '));
        // This is the explicit execution boundary for learner-written JavaScript.
        // eslint-disable-next-line no-new-func
        const result = new Function('console', 'input', code)({ log:write, error:write, warn:write }, codeInput);
        if (result !== undefined) write(result);
        setCodeOutput(output.join('\n') || 'Program finished with no output.');
      }
      else {
        const loader = (window as any).loadPyodide;
        if (!loader) throw new Error('Python is still downloading. Check your connection, wait a moment, then run again.');
        pyodideReady ||= loader({ indexURL:'https://cdn.jsdelivr.net/pyodide/v314.0.6/full/' });
        const runtime = await pyodideReady; runtime.globals.set('user_code', code); runtime.globals.set('user_stdin', codeInput);
        const output = await runtime.runPythonAsync("import io, sys, traceback\n_capture = io.StringIO()\n_stdout, _stdin = sys.stdout, sys.stdin\nsys.stdout, sys.stdin = _capture, io.StringIO(user_stdin)\ntry:\n    exec(user_code, {})\nexcept Exception:\n    traceback.print_exc(file=_capture)\nfinally:\n    sys.stdout, sys.stdin = _stdout, _stdin\n_capture.getvalue() or 'Program finished with no output.'");
        setCodeOutput(String(output));
      }
      save({ ...state, codePassed:true });
    } catch (error:any) { setCodeOutput(error?.message || String(error)); }
    finally { setCodeBusy(false); }
  };
  const checkQuiz = () => save({ ...state, quizScore: quizChoice === 'feedback' ? 100 : 0 });
  const assessmentQuestions = [
    { prompt:'Which activity best validates an engineering solution?', options:[['theory','Reading theory only'],['prototype','Building and testing a prototype'],['assume','Assuming the first design works']], answer:'prototype' },
    { prompt:'A result differs from your expected output. What should you do next?', options:[['repeat','Repeat the same test without checking inputs'],['isolate','Check units, inputs, and one variable at a time'],['ignore','Ignore the result because the design looks correct']], answer:'isolate' },
    { prompt:'Which portfolio evidence is most convincing?', options:[['claim','A claim that you know a tool'],['demo','A documented project with setup, results, and source code'],['certificate','A certificate with no project evidence']], answer:'demo' },
  ];
  const submitAssessmentAnswer = async () => {
    if (!assessmentChoice) { setAssessmentResult('Choose an answer before continuing.'); return; }
    const nextAnswers = [...assessmentAnswers, assessmentChoice];
    setAssessmentAnswers(nextAnswers); setAssessmentChoice(''); setAssessmentResult('');
    if (assessmentStep < assessmentQuestions.length - 1) { setAssessmentStep(assessmentStep + 1); return; }
    const correct = nextAnswers.filter((answer, index) => answer === assessmentQuestions[index].answer).length;
    const score = Math.round(correct / assessmentQuestions.length * 100);
    const level = score >= 80 ? 'Applied ready' : score >= 50 ? 'Foundation builder' : 'Foundation review';
    await recordAssessment(score, level);
    setAssessmentResult(`${correct}/${assessmentQuestions.length} correct · Recommended level: ${level}. ${score >= 80 ? 'Build a small project and move to applied practice.' : 'Review the weak areas in the heatmap, then retry.'}`);
  };
  const restartAssessment = () => { setAssessmentStep(0); setAssessmentAnswers([]); setAssessmentChoice(''); setAssessmentResult(''); };
  const issueCertificate = async () => {
    if (completedLessons.length < 10) { setCertificateError('Complete at least 10 lessons to unlock a verified certificate.'); return; }
    setIssuingCertificate(true); setCertificateError('');
    try {
      const token = await user.getIdToken();
      const response = await axios.post(`${API}/api/certificates/issue`, { track_title: 'Engineer Made learning milestone' }, { headers: { Authorization: `Bearer ${token}` } });
      setCertificateCode(response.data.code);
    } catch (error: any) { setCertificateError(error?.response?.data?.detail || 'The certificate service is temporarily unavailable.'); }
    finally { setIssuingCertificate(false); }
  };
  const askTutor = async (suggested?: string) => {
    const question = (suggested || tutorQuestion).trim(); if (!question || tutorBusy) return;
    const next = [...tutorMessages, {role:'user' as const,text:question}]; setTutorMessages(next); setTutorQuestion(''); setTutorBusy(true); setTutorError('');
    try { const response = await axios.post(`${API}/api/ai-tutor/chat`, {message:question,history:tutorMessages,learner_name:profile?.name || user.displayName || 'Engineer'}); setTutorMessages([...next,{role:'assistant',text:response.data.answer}]); }
    catch (error:any) { setTutorError(error?.response?.data?.detail || 'The tutor could not respond. Check that the backend is running and Gemini is configured.'); }
    finally { setTutorBusy(false); }
  };
  const speak = (text:string) => { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.rate=.95; window.speechSynthesis.speak(utterance); };
  const startVoice = async () => {
    const Recognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!Recognition) { setTutorError('Voice input is not supported in this browser. Use the latest Chrome or Edge, or type your question.'); return; }
    if (!navigator.mediaDevices?.getUserMedia) { setTutorError('This browser cannot access a microphone. Use the latest Chrome or Edge, or type your question.'); return; }

    setTutorError('');
    let stream: MediaStream | null = null;
    let receivedTranscript = false;
    let receivedError = false;
    const stopMicrophone = () => stream?.getTracks().forEach(track => track.stop());

    try {
      // Request the selected microphone first so a device/busy/permission error
      // is reported clearly before Chrome's speech service starts.
      stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      stopMicrophone();
      stream = null;
      const recognition = new Recognition();
      recognition.lang = 'en-IN';
      recognition.interimResults = false;
      recognition.continuous = false;
      recognition.maxAlternatives = 1;
      recognition.onresult = (event: any) => {
        receivedTranscript = true;
        setTutorQuestion(event.results[0][0].transcript);
      };
      recognition.onerror = (event: any) => {
        receivedError = true;
        const errors: Record<string, string> = {
          'not-allowed': 'Microphone access was denied by the browser. Check the site permission, then reload.',
          'service-not-allowed': 'Chrome speech recognition is disabled. Check Chrome microphone and speech service settings.',
          'audio-capture': 'Chrome cannot use the selected microphone. Close any app using it, select another microphone, then retry.',
          'network': 'Chrome could not reach its speech-recognition service. Check your internet connection and retry.',
          'no-speech': 'No speech was detected. Press the microphone and speak clearly after it starts.',
          'aborted': 'Voice input was interrupted. Close other microphone apps and retry.',
        };
        setTutorError(errors[event.error] || `Voice input failed (${event.error || 'unknown error'}). Type your question or retry.`);
      };
      recognition.onend = () => { setIsListening(false);
        stopMicrophone();
        if (!receivedTranscript && !receivedError) setTutorError('No speech was detected. Press the microphone and speak after it starts.');
      };
      setIsListening(true); recognition.start();
    } catch (error: any) {
      stopMicrophone(); setIsListening(false);
      const name = error?.name || '';
      if (name === 'NotAllowedError' || name === 'SecurityError') setTutorError('Chrome could not access the microphone. Check the site permission and Windows microphone privacy settings, then reload.');
      else if (name === 'NotFoundError') setTutorError('No microphone was found. Connect or select a microphone in Chrome settings, then retry.');
      else if (name === 'NotReadableError') setTutorError('The microphone is busy or unavailable. Close Teams, Meet, Discord, or another microphone app, then retry.');
      else setTutorError('Microphone setup failed. Type your question or retry after checking your microphone device.');
    }
  };
  const addBookmark = async () => {
    const title = bookmarkTitle.trim(); const url = bookmarkUrl.trim();
    if (!title || !/^https?:\/\//i.test(url)) { setBookmarkError('Enter a resource title and a valid https:// link.'); return; }
    await saveBookmark({ title, url }); setBookmarkTitle(''); setBookmarkUrl(''); setBookmarkError('');
  };
  const formatTimer = (seconds: number) => `${String(Math.floor(seconds / 60)).padStart(2,'0')}:${String(seconds % 60).padStart(2,'0')}`;
  const chooseTimer = (minutes: number) => { setTimerRunning(false); setTimerPreset(minutes); setTimerSeconds(minutes * 60); };
  const saveDoubt = () => {
    if (!doubtText.trim()) return;
    save({ ...state, doubts: [{ text:doubtText.trim(), createdAt:new Date().toISOString() }, ...state.doubts].slice(0,30) }); setDoubtText('');
  };
  const shareReferral = async () => {
    const url = `${window.location.origin}/signup?ref=${encodeURIComponent(user.uid)}`;
    try { await navigator.share({ title:'Engineer Made', text:'I am using Engineer Made for engineering learning roadmaps.', url }); }
    catch { await navigator.clipboard.writeText(url); }
  };
  const downloadWallpaper = () => {
    const surface = document.createElement('canvas'); surface.width=1440; surface.height=900; const context=surface.getContext('2d'); if (!context) return;
    const gradient=context.createLinearGradient(0,0,1440,900); gradient.addColorStop(0,'#071323'); gradient.addColorStop(.5,'#17244b'); gradient.addColorStop(1,'#6d4b13'); context.fillStyle=gradient; context.fillRect(0,0,1440,900); context.fillStyle='#f6df9f'; context.font='bold 68px Georgia'; context.textAlign='center'; const words=wallpaperText.trim().slice(0,120).split(' '); const rows:string[]=[]; let row=''; words.forEach(word=>{const next=`${row} ${word}`.trim();if(context.measureText(next).width>1100){rows.push(row);row=word;}else row=next;});if(row)rows.push(row); rows.forEach((line,index)=>context.fillText(line,720,390+index*92)); context.font='28px Arial';context.fillStyle='#d8caa9';context.fillText('Engineer Made · your personal study reminder',720,720); const link=document.createElement('a');link.download='engineer-made-wallpaper.png';link.href=surface.toDataURL('image/png');link.click();
  };
  const draw = (event: React.PointerEvent<HTMLCanvasElement>) => { const surface=canvasRef.current; if(!surface || !drawing.current) return; const bounds=surface.getBoundingClientRect(); const context=surface.getContext('2d'); if(!context) return; context.lineCap='round';context.lineJoin='round';context.strokeStyle=penColor;context.lineWidth=penSize;context.lineTo((event.clientX-bounds.left)*surface.width/bounds.width,(event.clientY-bounds.top)*surface.height/bounds.height);context.stroke();context.beginPath();context.moveTo((event.clientX-bounds.left)*surface.width/bounds.width,(event.clientY-bounds.top)*surface.height/bounds.height); };
  const startDrawing = (event: React.PointerEvent<HTMLCanvasElement>) => { drawing.current=true; event.currentTarget.setPointerCapture(event.pointerId); const context=event.currentTarget.getContext('2d'); const bounds=event.currentTarget.getBoundingClientRect(); context?.beginPath();context?.moveTo((event.clientX-bounds.left)*event.currentTarget.width/bounds.width,(event.clientY-bounds.top)*event.currentTarget.height/bounds.height); };
  const clearBoard = () => { const surface=canvasRef.current; const context=surface?.getContext('2d'); if(surface&&context) context.clearRect(0,0,surface.width,surface.height); };
  const saveBoard = () => { const surface=canvasRef.current; if(!surface) return; const link=document.createElement('a');link.download='engineer-made-whiteboard.png';link.href=surface.toDataURL('image/png');link.click(); };
  const downloadNote = (saved:{text:string;date:string}) => { const page = window.open('', '_blank'); if (!page) return; page.document.write(`<title>Engineer Made note</title><main><h1>Learning note</h1><p>${saved.date}</p><article>${saved.text.replace(/</g,'&lt;').replace(/\n/g,'<br>')}</article></main><style>body{font:16px Georgia,serif;padding:40px;color:#171717}h1{margin-bottom:6px}p{color:#666}article{white-space:normal;line-height:1.6;border-top:1px solid #ddd;padding-top:24px}</style>`); page.document.close(); page.focus(); page.print(); };
  const downloadResume = () => {
    const text = `${profile?.name || user.displayName}\n${resumeHeadline}\n${profile?.email || user.email}\n${profile?.collegeName || ''}\n\nSUMMARY\n${resumeSummary}\n\nSKILLS\n${resumeSkills}\n\nPROJECTS\n${state.projects.map(p => `- ${p.title}: ${p.github}`).join('\n') || 'Add GitHub projects in the Projects section.'}\n\nLEARNING\n${completedLessons.length} lessons completed in Engineer Made`;
    const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = 'engineering-resume.txt'; a.click(); URL.revokeObjectURL(url);
  };
  const generateResumeSuggestions = async () => {
    const draft = `Candidate: ${profile?.name || user.displayName || 'Engineering student'}\nHeadline: ${resumeHeadline}\nSummary: ${resumeSummary}\nSkills: ${resumeSkills}\nProjects: ${state.projects.map(project => project.title).join(', ') || 'None yet'}`;
    if (!resumeHeadline.trim() && !resumeSummary.trim() && !resumeSkills.trim()) { setResumeError('Write at least one resume section before asking for suggestions.'); return; }
    setResumeBusy(true); setResumeError(''); setResumeSuggestions('');
    try { const response = await axios.post(`${API}/api/ai-tutor/chat`, { message:`Review this engineering student resume draft. Give 5 concise, honest improvements. Do not invent experience, achievements, marks, or skills.\n\n${draft}`, history: [], learner_name: profile?.name || user.displayName || 'Engineer' }); setResumeSuggestions(response.data.answer); }
    catch (error: any) { setResumeError(error?.response?.data?.detail || 'AI suggestions are unavailable. Check the Gemini service and retry.'); }
    finally { setResumeBusy(false); }
  };
  const runAdaptivePractice = async () => {
    if (!practiceChoice) { setPracticeResult('Choose an answer first.'); return; }
    const score = practiceChoice === 'validate' ? 100 : practiceChoice === 'measure' ? 60 : 20;
    await recordAssessment(score, score >= 80 ? 'Applied practice' : 'Foundation review');
    setPracticeResult(score === 100 ? 'Correct. Validation with measurable evidence is the strongest engineering decision.' : 'Revision focus: define a measurable test, then validate the result before concluding.');
  };
  const generateStudyAsset = async (kind: 'summary' | 'cheatsheet') => {
    if (!smartTopic.trim() || smartBusy) return;
    setSmartBusy(true); setSmartResult(''); setTutorError('');
    const instruction = kind === 'summary' ? `Summarize this for an engineering learner in 5 clear bullet points, including one practical example: ${smartTopic}` : `Create a concise engineering revision cheatsheet for this topic. Include key concepts, a mini checklist, one common mistake, and one practical example: ${smartTopic}`;
    try { const response = await axios.post(`${API}/api/ai-tutor/chat`, { message: instruction, history: [], learner_name: profile?.name || user.displayName || 'Engineer' }); setSmartResult(response.data.answer); }
    catch (error: any) { setTutorError(error?.response?.data?.detail || 'Gemini could not create this study asset. Please retry after checking the AI service configuration.'); }
    finally { setSmartBusy(false); }
  };
  const selectDoubtReference = (file?: File) => {
    setDoubtFile(file || null); setDoubtFileName(file?.name || ''); setDoubtPreview('');
    if (file?.type.startsWith('image/')) { const reader = new FileReader(); reader.onload = () => setDoubtPreview(String(reader.result || '')); reader.readAsDataURL(file); }
  };
  const askDoubtTutor = async () => {
    if (!doubtDescription.trim() || doubtBusy) return;
    setDoubtBusy(true); setDoubtResult('');
    const prompt = `Act as an engineering tutor. The learner has a ${doubtKind.toLowerCase()}${doubtFileName ? ` and attached a local reference named ${doubtFileName}` : ''}. Their description: ${doubtDescription}. Explain likely causes, a step-by-step diagnostic approach, and one safe next action.`;
    try {
      if (doubtFile) { const form = new FormData(); form.append('file', doubtFile); form.append('context', doubtDescription); form.append('doubt_kind', doubtKind); const token = await user.getIdToken(); const response = await axios.post(`${API}/api/ai-tutor/vision`, form, { headers:{ Authorization:`Bearer ${token}` } }); setDoubtResult(response.data.answer); }
      else { const response = await axios.post(`${API}/api/ai-tutor/chat`, { message: prompt, history: [], learner_name: profile?.name || user.displayName || 'Engineer' }); setDoubtResult(response.data.answer); }
    }
    catch { setDoubtResult('Start by writing the expected result, actual result, inputs and constraints. Isolate one variable at a time, verify units or error output, then test the smallest reproducible example.'); }
    finally { setDoubtBusy(false); }
  };
  const analyseRepository = async () => {
    if (!repoUrl.trim() || repoBusy) return;
    setRepoBusy(true); setRepoResult(''); setRepoRubric(null);
    try { const token = await user.getIdToken(); const response = await axios.post(`${API}/api/github/repository-analysis`, { url:repoUrl }, { headers:{ Authorization:`Bearer ${token}` } }); setRepoRubric(response.data); }
    catch (error:any) { setRepoResult(error?.response?.data?.detail || 'GitHub analysis is unavailable. Check the public repository URL and retry.'); }
    finally { setRepoBusy(false); }
  };

  const show = (feature: string) => !activeFeature || activeFeature === feature;
  const details = activeFeature ? featureInfo[activeFeature] : undefined;
  const dailyTasks = [
    { id:'daily-concept', icon:'🧠', title:'Review one core engineering concept', xp:20, target:'quiz' },
    { id:'daily-practice', icon:'🎯', title:'Complete one adaptive practice task', xp:30, target:'adaptive-practice' },
    { id:'daily-portfolio', icon:'🚀', title:'Improve one portfolio or project detail', xp:25, target:'projects' },
  ];
  const completeChallenge = async (id: string) => {
    if (state.completedChallenges.includes(id)) return;
    setDailyError('');
    try {
      const token = await user.getIdToken();
      const response = await axios.post(`${API}/api/learner/daily-challenges/complete`, { challenge_id:id }, { headers:{ Authorization:`Bearer ${token}` } });
      save({ ...state, completedChallenges:[...state.completedChallenges, id], challengeDate: response.data.date || new Date().toISOString().slice(0, 10) });
      setDailyStatus({ xp:response.data.xp, streak:response.data.streak });
    } catch (error: any) { setDailyError(error?.response?.data?.detail || 'Daily challenge progress could not be saved. Please retry.'); }
  };
  return <div className={`hub-page ${embedded ? 'hub-embedded feature-workspace' : ''}`}>
    {!embedded && <header className="hub-header"><span className="dashboard-kicker">ENGINEERING CAREER HUB</span><h1>Learn, practise, build and get hired</h1><p>All your learning tools in one local workspace.</p></header>}
    {details && activeFeature !== 'ai-tutor' && <><header className="feature-detail-hero"><div className="feature-hero-icon">{details.icon}</div><div><span className="dashboard-kicker">LEARNER TOOL</span><h1>{details.title}</h1><p>{details.description}</p></div></header><div className="feature-metrics">{details.metrics.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div></>}
    <div key={activeFeature || 'all-tools'} className={activeFeature ? `feature-detail-layout feature-switch ${activeFeature === 'ai-tutor' ? 'tutor-full-layout' : ''}` : ''}><div className={`hub-grid ${activeFeature ? 'single-feature' : ''}`}>
      {show('recommendation') && <section className="hub-card hub-wide"><h2>✨ Personalized recommendation</h2><h3>{recommendation}</h3><p>Based on your {profile?.educationStatus || 'learner'} profile at {profile?.collegeName || 'your college'}.</p><Link to="/paths" className="hub-link">Choose a recommended roadmap →</Link></section>}
      {show('continue') && <section className="hub-card hub-wide"><h2>▶ Continue learning</h2>{history.length ? history.slice(0,3).map((item:any) => <Link key={item.url} to={item.url}>{item.title}</Link>) : <p>Open a lesson to start your history.</p>}<h2 className="recent-heading">🕘 Recently watched</h2><p>{history.length} recent lessons</p>{history.slice(0,4).map((item:any) => <small key={item.url}>{item.title}</small>)}</section>}
      {show('quiz') && <section className="hub-card hub-wide"><h2>🧠 Module quiz</h2><p>Use this short quiz after a roadmap lesson. Flashcards are now a separate sidebar tool.</p><p>What helps an engineer improve a design?</p><select value={quizChoice} onChange={e=>setQuizChoice(e.target.value)}><option value="">Choose an answer</option><option value="guess">Ignoring test results</option><option value="feedback">Testing and feedback</option><option value="copy">Copying without analysis</option></select><button onClick={checkQuiz}>Check answer</button>{state.quizScore > 0 && <b className="success">Correct — 100%</b>}<h3>Practice programs</h3><ol><li>Read two numbers and print their sum.</li><li>Find the largest value in a list.</li><li>Validate whether an input is empty.</li></ol><button onClick={()=>onFeatureChange?.('coding')}>Open coding practice →</button></section>}
      {show('flashcards') && (() => { const cards=[['What is validation?','Testing a result against a measurable requirement.'],['Why use small tests first?','They isolate errors before a system becomes complex.'],['What should a project README show?','Problem, setup, solution, and evidence of results.']]; const card=cards[flashcardIndex % cards.length]; const known=state.flashcardsKnown.includes(String(flashcardIndex % cards.length)); return <section className="hub-card hub-wide"><h2><span className="flashcard-logo">🗂️</span> Flashcards</h2><p>{state.flashcardsKnown.length}/{cards.length} cards marked known. Say the answer aloud before revealing it.</p><button className={`flashcard ${flashcardFlipped ? 'is-flipped' : ''}`} onClick={()=>setFlashcardFlipped(value=>!value)}><small>{flashcardFlipped ? 'ANSWER' : 'PROMPT'}</small><b>{flashcardFlipped ? card[1] : card[0]}</b><span>Click to {flashcardFlipped ? 'hide answer' : 'reveal answer'}</span></button><div className="flashcard-actions"><button onClick={()=>{const id=String(flashcardIndex % cards.length); save({...state,flashcardsKnown:known ? state.flashcardsKnown.filter(item=>item!==id) : [...state.flashcardsKnown,id]});}}>{known ? 'Mark for review' : 'Mark known'}</button><button onClick={()=>{setFlashcardIndex(index=>(index+1)%cards.length);setFlashcardFlipped(false);}}>Next card →</button></div></section>; })()}
      {show('focus-timer') && <section className="hub-card hub-wide"><h2>🍅 Focus timer</h2><p>A completed session is recorded only after the countdown reaches zero.</p><div className="timer-workspace"><div className="timer-face"><small>FOCUS SESSION</small><strong>{formatTimer(timerSeconds)}</strong><span>{timerRunning ? 'Timer running' : timerSeconds === 0 ? 'Session completed' : 'Ready when you are'}</span></div><div className="tool-panel"><b>Session length</b><div className="tool-actions">{[25,50,15].map(minutes=><button className={timerPreset===minutes ? 'active' : ''} onClick={()=>chooseTimer(minutes)} key={minutes}>{minutes} min</button>)}</div><input value={focusSubject} onChange={e=>setFocusSubject(e.target.value)} placeholder="What are you studying?" /><div className="tool-actions"><button onClick={()=>{if(timerRunning)setTimerRunning(false);else{if(timerSeconds===0)setTimerSeconds(timerPreset*60);setTimerRunning(true);}}}>{timerRunning ? 'Pause' : timerSeconds === 0 ? 'Start another session' : 'Start'}</button><button onClick={()=>chooseTimer(timerPreset)}>Reset</button></div><small>{state.focusMinutes} recorded focus minutes · {state.focusSessions.length} completed sessions</small></div></div>{state.focusSessions.slice(0,5).map((session,index)=><div className="activity-row" key={`${session.completedAt}-${index}`}><span>🍅</span><div><b>{session.subject}</b><small>{session.minutes} min · {new Date(session.completedAt).toLocaleString()}</small></div></div>)}</section>}
      {show('focus-music') && <section className="hub-card"><h2>🎵 Focus music</h2><p>These are direct YouTube links. Engineer Made does not simulate playback or claim to host the music.</p><div className="resource-list">{[['Lofi Girl — lofi hip hop radio','https://www.youtube.com/watch?v=jfKfPfyJRdk'],['Ambient study music','https://www.youtube.com/results?search_query=ambient+study+music'],['Brown noise for focus','https://www.youtube.com/results?search_query=brown+noise+for+focus']].map(([name,url])=><a className="hub-link" href={url} target="_blank" rel="noreferrer" key={url}>▶ {name}</a>)}</div></section>}
      {show('doubt-forum') && <section className="hub-card hub-wide"><h2>👥 Doubt workspace</h2><p>Save a precise doubt here, then send it to the AI tutor. These are private browser notes—not public posts or fake community answers.</p><textarea value={doubtText} onChange={e=>setDoubtText(e.target.value)} placeholder="Describe the concept, expected result, actual result, and any error message…" /><div className="tool-actions"><button onClick={saveDoubt}>Save doubt</button><button onClick={()=>{if(doubtText.trim()) setTutorQuestion(doubtText.trim()); onFeatureChange?.('ai-tutor');}}>Open in AI tutor →</button></div>{state.doubts.length ? state.doubts.map((doubt,index)=><div className="activity-row" key={`${doubt.createdAt}-${index}`}><span>❓</span><div><b>{doubt.text}</b><small>Saved {new Date(doubt.createdAt).toLocaleString()}</small></div></div>) : <p className="empty-state">No saved doubts yet.</p>}</section>}
      {show('refer-friends') && <section className="hub-card hub-wide"><h2>🤝 Refer a friend</h2><p>Share a personal sign-up link. Referral counts and rewards are intentionally not displayed until server-side attribution is built.</p><div className="bookmark-form"><input readOnly value={`${window.location.origin}/signup?ref=${encodeURIComponent(user.uid)}`} aria-label="Your referral link" /><button onClick={()=>void shareReferral()}>Share or copy link</button></div></section>}
      {show('themes') && <section className="hub-card"><h2>🌈 Theme customizer</h2><p>Theme choice is stored on this device and applies immediately.</p><div className="theme-options">{[['royal','Royal'],['ocean','Ocean'],['forest','Forest'],['saffron','Saffron']].map(([id,label])=><button className={`theme-option ${theme===id ? 'active' : ''} ${id}`} onClick={()=>setTheme(id)} key={id}><i/><i/><i/><b>{label}</b></button>)}</div></section>}
      {show('my-story') && <section className="hub-card hub-wide"><h2>🤖 My learning story</h2><p>Creates a factual reflection from activity already saved in Engineer Made.</p><button onClick={()=>setStory(`${profile?.name || user.displayName || 'This learner'} has completed ${completedLessons.length} roadmap lesson${completedLessons.length===1?'':'s'}, recorded ${assessmentAttempts.length} assessment attempt${assessmentAttempts.length===1?'':'s'}, added ${state.projects.length} GitHub project${state.projects.length===1?'':'s'}, and completed ${state.focusSessions.length} focus session${state.focusSessions.length===1?'':'s'}. Next step: choose one concrete lesson or project task and complete it.`)}>Generate my factual summary</button>{story && <div className="result-panel"><b>Your activity summary</b><p>{story}</p><button onClick={()=>navigator.clipboard.writeText(story)}>Copy summary</button></div>}</section>}
      {show('wallpapers') && <section className="hub-card"><h2>🖼️ Study wallpaper</h2><p>Generate a PNG with your own message; no stock progress claims are included.</p><input value={wallpaperText} maxLength={120} onChange={e=>setWallpaperText(e.target.value)} placeholder="Your study reminder" /><button onClick={downloadWallpaper}>Download wallpaper PNG</button></section>}
      {show('performance') && <section className="hub-card hub-wide"><h2>📈 Performance dashboard</h2>{assessmentAttempts.length ? <div className="performance-bars">{assessmentAttempts.slice(0,7).reverse().map((attempt,index)=><article key={attempt.id}><span>Attempt {index+1}</span><i style={{height:`${Math.max(8,attempt.score)}%`}} /><b>{attempt.score}%</b></article>)}</div> : <div className="empty-state">No assessments recorded yet. Complete an assessment to see your real score history.</div>}<div className="analytics-row"><span>Focus time</span><b>{state.focusMinutes} min</b><div className="progress-track"><i style={{width:`${Math.min(100,state.focusMinutes/3)}%`}} /></div></div></section>}
      {show('badges') && <section className="hub-card hub-wide"><h2>🏅 Activity-based badges</h2><p>Badges unlock only from activity recorded in this account. They are not certificates.</p><div className="badge-grid">{[['First lesson',completedLessons.length>=1,'Complete 1 lesson'],['Practice started',assessmentAttempts.length>=1,'Complete 1 assessment'],['Focus builder',state.focusSessions.length>=3,'Complete 3 focus sessions'],['Project builder',state.projects.length>=1,'Add 1 GitHub project'],['Roadmap explorer',completedLessons.length>=10,'Complete 10 lessons']].map(([name,unlocked,rule])=><article className={unlocked ? 'unlocked' : ''} key={String(name)}><span>{unlocked?'🏅':'🔒'}</span><b>{name}</b><small>{unlocked?'Unlocked from your activity':String(rule)}</small></article>)}</div></section>}
      {show('loot-box') && <section className="hub-card"><h2>🎁 Study prompt box</h2><p>This gives a next action, not fictional XP or rewards.</p><button onClick={()=>setStudyPrompt(['Write the input, expected output, and pass condition for your current project.','Turn one lesson heading into three flashcards in your own words.','Review one saved doubt and identify the smallest reproducible example.','Improve one README section: problem, setup, or evidence of results.'][Math.floor(Math.random()*4)])}>Draw a study prompt</button>{studyPrompt && <div className="result-panel"><b>Your next action</b><p>{studyPrompt}</p></div>}</section>}
      {show('whiteboard') && <section className="hub-card hub-wide"><h2>🎨 Whiteboard</h2><div className="whiteboard-controls"><input type="color" value={penColor} onChange={e=>setPenColor(e.target.value)} aria-label="Pen colour" /><label>Pen size <input type="range" min="1" max="16" value={penSize} onChange={e=>setPenSize(Number(e.target.value))} /></label><button onClick={clearBoard}>Clear</button><button onClick={saveBoard}>Save PNG</button></div><canvas className="learning-whiteboard" ref={canvasRef} width="1400" height="720" onPointerDown={startDrawing} onPointerMove={draw} onPointerUp={()=>{drawing.current=false;}} onPointerLeave={()=>{drawing.current=false;}} aria-label="Interactive whiteboard" /></section>}
      {show('coding') && <section className="hub-card hub-wide compiler-workspace"><header><div><h2>💻 Free browser coding practice</h2><p>Python and JavaScript run directly in your browser. No server, VPS, API key, or payment is required.</p></div><select value={codeLanguage} onChange={e=>changeCodeLanguage(e.target.value as 'python' | 'javascript')}><option value="python">Python</option><option value="javascript">JavaScript</option></select></header><div className="compiler-split"><section><label>Code editor</label><textarea className="code-editor" value={code} onChange={e=>setCode(e.target.value)} spellCheck={false} /><label>Standard input (optional)</label><textarea className="compiler-input" value={codeInput} onChange={e=>setCodeInput(e.target.value)} placeholder="Input passed to your program" /></section><section className="compiler-console"><label>Output</label><pre>{codeOutput}</pre><button onClick={runCode} disabled={codeBusy || !code.trim()}>{codeBusy ? 'Running…' : 'Run code ▶'}</button></section></div></section>}
      {show('projects') && <section className="hub-card hub-wide project-galaxy"><div className="project-galaxy-scene" aria-hidden="true"><i/><i/><i/></div><h2>🚀 GitHub projects</h2><div className="resume-grid"><div className="project-form"><input placeholder="Project title" value={projectTitle} onChange={e=>setProjectTitle(e.target.value)} /><input placeholder="https://github.com/user/repo" value={github} onChange={e=>setGithub(e.target.value)} /><button onClick={addProject}>Add to my private project list</button>{projectError && <div className="tutor-error">⚠ {projectError}</div>}</div><aside className="resume-preview"><small>PRIVATE PROJECTS · ONLY YOU</small>{state.projects.length ? state.projects.map(p=><a href={p.github} target="_blank" rel="noreferrer" key={p.github}><b>{p.title}</b><small>{p.github}</small></a>) : <p>Your GitHub projects will be listed here after you add them.</p>}</aside></div></section>}
      {show('certificates') && <section className="hub-card achievement-card"><span className="achievement-medallion" aria-hidden="true">✦</span><h2>🏆 Certificates & badges</h2><strong className="big-number">{completedLessons.length}</strong><p>lessons completed · {Math.max(0,10-completedLessons.length)} until verified certificate</p><span className="badge">{completedLessons.length >= 10 ? 'Roadmap Explorer' : 'Rising Engineer'}</span><button onClick={issueCertificate} disabled={issuingCertificate || completedLessons.length < 10}>{issuingCertificate ? 'Creating credential…' : 'Create verified certificate'}</button>{certificateCode && <div className="result-panel"><b>Credential created: {certificateCode}</b><p>Share this verification link with employers or colleges.</p><Link to={`/verify-certificate/${certificateCode}`}>Verify this certificate →</Link><button onClick={()=>window.print()}>Print certificate</button></div>}{certificateError && <div className="tutor-error">⚠ {certificateError}</div>}<Link to="/verify-certificate" className="hub-link">Verify an existing certificate →</Link></section>}
      {show('bookmarks') && <section className="hub-card"><h2>🔖 Saved courses & bookmarks</h2><p>On any lesson page, use <b>Save lesson</b>. You can also save a useful external resource below.</p><div className="bookmark-form"><input placeholder="Resource title" value={bookmarkTitle} onChange={e=>setBookmarkTitle(e.target.value)} /><input placeholder="https://example.com/resource" value={bookmarkUrl} onChange={e=>setBookmarkUrl(e.target.value)} /><button onClick={()=>void addBookmark()}>Save resource</button></div>{bookmarkError && <div className="tutor-error">⚠ {bookmarkError}</div>}{bookmarks.length ? bookmarks.map(bookmark=><div className="activity-row" key={bookmark.id}><span>🔖</span><div><a href={bookmark.url} target={bookmark.url.startsWith('/') ? undefined : '_blank'} rel="noreferrer"><b>{bookmark.title}</b></a><small>Saved {new Date(bookmark.savedAt).toLocaleDateString()}</small></div><button onClick={()=>removeBookmark(bookmark.id)}>Remove</button></div>) : <div className="empty-state">No saved resources yet. Open a lesson and select “Save lesson”, or paste a helpful resource link above.</div>}</section>}
      {show('notes') && <section className="hub-card hub-wide"><h2>📝 Notes library</h2><textarea placeholder="Write a learning note…" value={note} onChange={e=>setNote(e.target.value)} /><button onClick={addNote}>Save note</button><div className="note-library">{state.notes.map((n,i)=><article className="note-paper" tabIndex={0} onClick={()=>setOpenedNote(n)} onKeyDown={e=>e.key==='Enter'&&setOpenedNote(n)} key={`${n.date}-${i}`}><span>📄</span><div><b>{n.text.split(/\s+/).slice(0,6).join(' ')}</b><small>Saved {n.date} · Open note</small></div></article>)}{!state.notes.length && <p className="empty-state">Your saved notes will appear here as papers.</p>}</div>{openedNote && <div className="result-panel note-opened"><header><b>Opened note · {openedNote.date}</b><div className="note-actions"><button onClick={()=>downloadNote(openedNote)}>Download as PDF</button><button onClick={()=>setOpenedNote(null)}>Close</button></div></header><p>{openedNote.text}</p></div>}</section>}
      {show('resume') && <section className="hub-card hub-wide resume-builder"><header><div><h2>📄 Build your resume</h2><p>You write the content. AI only suggests improvements based on what you provide.</p></div><button onClick={downloadResume}>Download draft</button></header><div className="resume-grid"><section className="resume-form"><label>Professional headline<input value={resumeHeadline} onChange={e=>setResumeHeadline(e.target.value)} placeholder="AI & Data Science student | Python | ML projects" /></label><label>Professional summary<textarea value={resumeSummary} onChange={e=>setResumeSummary(e.target.value)} placeholder="Write 2–3 honest lines about your learning focus, projects, and goal…" /></label><label>Skills<input value={resumeSkills} onChange={e=>setResumeSkills(e.target.value)} placeholder="Python, SQL, Machine Learning, React" /></label><button onClick={()=>void generateResumeSuggestions()} disabled={resumeBusy}>{resumeBusy ? 'Reviewing…' : 'Get AI suggestions'}</button>{resumeError && <div className="tutor-error">⚠ {resumeError}</div>}{resumeSuggestions && <pre className="smart-output">{resumeSuggestions}</pre>}</section><article className="resume-preview"><small>LIVE PREVIEW</small><h2>{profile?.name || user.displayName || 'Your name'}</h2><b>{resumeHeadline || 'Your professional headline'}</b><p>{profile?.email || user.email} · {profile?.collegeName || 'College name'}</p><h3>Profile</h3><p>{resumeSummary || 'Write an honest professional summary.'}</p><h3>Skills</h3><p>{resumeSkills || 'Add your technical skills.'}</p><h3>Projects</h3>{state.projects.length ? state.projects.map(project=><p key={project.github}><b>{project.title}</b> · {project.github}</p>) : <p>Add projects in the Projects section.</p>}</article></div></section>}
      {show('reports') && <section className="hub-card"><h2>🚩 Submit a content report</h2><p>Help us identify resources that need attention.</p><input placeholder="Video or lesson URL" value={reportUrl} onChange={e=>setReportUrl(e.target.value)} /><select value={reportReason} onChange={e=>setReportReason(e.target.value)}><option value="">Select issue</option><option>Broken video</option><option>Outdated content</option><option>Incorrect information</option></select><button onClick={()=>void report()}>Submit report</button><h3 className="recent-heading">Your report history</h3>{state.reports.length ? state.reports.map((item,index)=><div className="activity-row" key={`${item.url}-${index}`}><span>#{state.reports.length-index}</span><div><b>{item.reason}</b><small>{item.url}</small></div><em>{item.status || 'Saved locally'}</em></div>) : <div className="empty-state">✓ No content issues reported yet</div>}</section>}
      {show('goals') && <section className="hub-card"><h2>🎯 Weekly goal & notifications</h2><p>This weekend: finish {Math.min(state.goal, 3)} lesson{Math.min(state.goal,3) === 1 ? '' : 's'}, complete one quiz, and practise one program.</p><div className="goal-presets"><button onClick={()=>save({...state,goal:2})}>Light weekend · 2 lessons</button><button onClick={()=>save({...state,goal:4})}>Focused weekend · 4 lessons</button><button onClick={()=>save({...state,goal:6})}>Deep weekend · 6 lessons</button></div><label>{state.goal} lessons per week<input type="range" min="1" max="20" value={state.goal} onChange={e=>save({...state,goal:Number(e.target.value)})} /></label><button onClick={()=>Notification.requestPermission()}>Enable reminders</button></section>}
      {show('schedule') && <section className="hub-card"><h2>⏰ Schedule task</h2><p>Save a learning-summary schedule for <b>{profile?.email || user.email}</b>. Browser reminders work immediately. Sending mail needs a configured server email provider and scheduled job.</p><label>Frequency<select value={state.schedule?.frequency || 'weekly'} onChange={e=>save({...state,schedule:{frequency:e.target.value as 'daily'|'weekly',time:state.schedule?.time || '18:00',enabled:state.schedule?.enabled || false}})}><option value="daily">Daily task summary</option><option value="weekly">Weekly goal summary</option></select></label><label>Preferred time<input type="time" value={state.schedule?.time || '18:00'} onChange={e=>save({...state,schedule:{frequency:state.schedule?.frequency || 'weekly',time:e.target.value,enabled:state.schedule?.enabled || false}})} /></label><button onClick={()=>save({...state,schedule:{frequency:state.schedule?.frequency || 'weekly',time:state.schedule?.time || '18:00',enabled:true}})}>Save schedule</button>{state.schedule?.enabled && <div className="result-panel"><b>Schedule saved</b><p>{state.schedule.frequency === 'daily' ? 'Daily learning summary' : 'Weekly goals summary'} at {state.schedule.time}. Email delivery will activate once the server mail provider is configured.</p></div>}</section>}
      {show('languages') && <section className="hub-card"><h2>🌐 Language lessons</h2><select value={state.language} onChange={e=>save({...state,language:e.target.value})}><option>English</option><option>Hindi</option><option>Tamil</option><option>Telugu</option><option>Kannada</option><option>Malayalam</option><option>Marathi</option><option>Bengali</option></select><p>Preferred roadmap video language: <b>{state.language}</b></p><a className="hub-link" href={`https://www.youtube.com/results?search_query=${encodeURIComponent(`${profile?.careerPathId?.replace(/-/g,' ') || 'engineering'} roadmap tutorial ${state.language}`)}`} target="_blank" rel="noreferrer">Find {state.language} roadmap videos →</a><small>Videos open from YouTube results in your chosen language; a curated per-language catalog is required before replacing every existing lesson video automatically.</small></section>}
      {show('ai-tutor') && <section className="ai-tutor-portal"><header className="tutor-status"><div className="tutor-avatar">🤖</div><div><h2>AI Tutor</h2><span><i /> Online · Gemini</span></div><span className={`ai-tutor-core ${tutorBusy ? 'is-thinking' : ''}`} aria-label={tutorBusy ? 'Tutor is thinking' : 'Tutor online'} /><button title="Clear conversation" onClick={()=>setTutorMessages(tutorMessages.slice(0,1))}>✨ New chat</button></header><div className="tutor-suggestions"><small>TRY ASKING</small><div>{['Explain Newton’s laws with examples','Difference between speed and velocity?','Explain thermodynamics in simple words','Help me choose CSE or ECE','Create a 7-day exam study plan','Explain Ohm’s law in Hinglish'].map(prompt=><button key={prompt} onClick={()=>askTutor(prompt)}>{prompt}</button>)}</div></div><div className="tutor-conversation">{tutorMessages.map((message,index)=><article className={`tutor-message ${message.role}`} key={index}>{message.role==='assistant' && <span className="tutor-avatar">🤖</span>}<div><small>{message.role==='assistant'?'AI TUTOR':'YOU'}</small><p>{message.text}</p>{message.role==='assistant' && <div className="message-actions"><button onClick={()=>speak(message.text)}>🔊 Listen</button><button onClick={()=>navigator.clipboard.writeText(message.text)}>📋 Copy</button></div>}</div></article>)}{tutorBusy && <div className="tutor-typing"><i/><i/><i/> Thinking about your question…</div>}{tutorError && <div className="tutor-error">⚠ {tutorError}</div>}</div><footer className="tutor-composer"><button className={`voice-button ${isListening ? 'is-listening' : ''}`} title="Speak your question" onClick={startVoice}>{isListening ? '🎙️ Listening…' : '🎙️'}</button><textarea aria-label="Ask the AI tutor" placeholder="Type or tap the microphone to speak (English / Hindi / Hinglish)" value={tutorQuestion} onChange={e=>setTutorQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();askTutor();}}}/><button className="send-button" disabled={!tutorQuestion.trim()||tutorBusy} onClick={()=>askTutor()}>Send →</button></footer><small className="tutor-disclaimer">AI can make mistakes. Verify important calculations and safety-critical guidance.</small></section>}
      {show('assessment') && (() => { const question=assessmentQuestions[assessmentStep]; return <section className="hub-card"><h2>🧩 Adaptive skill assessment</h2><p>Question {assessmentStep + 1} of {assessmentQuestions.length} · Your result updates the Skill Tree and Weakness Heatmap.</p><div className="question-box"><h3>{question.prompt}</h3></div>{question.options.map(([value,label])=><label className="choice-row" key={value}><input type="radio" name="assessment" value={value} checked={assessmentChoice===value} onChange={e=>setAssessmentChoice(e.target.value)} /> {label}</label>)}<button onClick={()=>void submitAssessmentAnswer()}>{assessmentStep === assessmentQuestions.length - 1 ? 'Finish assessment' : 'Next question →'}</button>{assessmentResult && <div className="result-panel"><b>Your result</b><p>{assessmentResult}</p><button onClick={restartAssessment}>Retake assessment</button></div>}{assessmentAttempts.length > 0 && <div className="assessment-history"><b>Recent attempts</b>{assessmentAttempts.slice(0,3).map(attempt=><small key={attempt.id}>{attempt.score}% · {attempt.level} · {new Date(attempt.completedAt).toLocaleDateString()}</small>)}</div>}</section>; })()}
      {show('groups') && <section className="hub-card"><h2>👥 Create a study group</h2><input placeholder="Group name, e.g. GATE Circuit Masters" value={groupName} onChange={e=>setGroupName(e.target.value)} /><select><option>Roadmap learning</option><option>Exam preparation</option><option>Project collaboration</option><option>Interview preparation</option></select><button onClick={()=>{if(groupName.trim()){save({...state,groups:[groupName.trim(),...state.groups]});setGroupName('');}}}>Create group</button>{state.groups.map((group,index)=><div className="activity-row" key={`${group}-${index}`}><span>👥</span><div><b>{group}</b><small>1 member · Invite classmates</small></div><em>Active</em></div>)}</section>}
      {show('simulations') && <section className="hub-card"><h2>⚙️ Engineering simulations lab</h2><p>Change an input, predict the result, then compare it with the live calculation.</p><div className="goal-presets"><button className={simulation==='circuit' ? 'active' : ''} onClick={()=>setSimulation('circuit')}>Circuit current</button><button className={simulation==='power' ? 'active' : ''} onClick={()=>setSimulation('power')}>Electrical power</button><button className={simulation==='beam' ? 'active' : ''} onClick={()=>setSimulation('beam')}>Beam load</button></div>{simulation !== 'beam' ? <><label>Supply voltage: <b>{voltage} V</b><input type="range" min="1" max="24" value={voltage} onChange={e=>setVoltage(Number(e.target.value))} /></label><label>Resistance: <b>{resistance} Ω</b><input type="range" min="1" max="20" value={resistance} onChange={e=>setResistance(Number(e.target.value))} /></label><div className="simulation-output"><span>{simulation==='circuit' ? 'Calculated current' : 'Calculated power'}</span><strong>{simulation==='circuit' ? `${(voltage/resistance).toFixed(2)} A` : `${(voltage*voltage/resistance).toFixed(1)} W`}</strong><small>{simulation==='circuit' ? 'I = V ÷ R' : 'P = V² ÷ R'}</small></div><div className="circuit-line"><i style={{opacity:Math.min(1,(voltage/resistance)/3)}} />🔋───💡───</div></> : <><label>Load at beam centre: <b>{simulationLoad} N</b><input type="range" min="10" max="200" step="10" value={simulationLoad} onChange={e=>setSimulationLoad(Number(e.target.value))} /></label><div className="simulation-output"><span>Estimated mid-span bending moment</span><strong>{(simulationLoad * 2 / 4).toFixed(1)} N·m</strong><small>M = W × L ÷ 4 · 2 m simply supported beam</small></div><div className="circuit-line">▰━━━━━━▼━━━━━━▰</div></>}</section>}
      {show('interviews') && <section className="hub-card"><h2>🎙️ Technical mock interview</h2><div className="question-box"><small>QUESTION 1 · PROBLEM SOLVING</small><h3>Tell me about an engineering problem you solved and how you validated the result.</h3></div><textarea placeholder="Structure your response using Situation, Task, Action and Result…" value={interviewAnswer} onChange={e=>setInterviewAnswer(e.target.value)} /><div className="interview-score"><span>Structure {interviewAnswer.length > 120 ? '✓' : '○'}</span><span>Technical detail {interviewAnswer.length > 240 ? '✓' : '○'}</span><span>Result {/result|improved|reduced|increased/i.test(interviewAnswer) ? '✓' : '○'}</span></div><button onClick={()=>setInterviewAnswer(interviewAnswer)}>Save practice answer</button></section>}
      {show('placement') && <section className="hub-card"><h2>🔒 Placement Preparation</h2><p>This feature is coming soon. It will contain verified, role-specific preparation tasks rather than an artificial readiness score.</p><span className="badge">COMING SOON</span></section>}
      {show('repo-analysis') && <section className="hub-card"><h2>🔎 Real GitHub portfolio review</h2><p>Analyzes public GitHub repository metadata and README availability through the GitHub API.</p><input placeholder="https://github.com/username/project" value={repoUrl} onChange={e=>setRepoUrl(e.target.value)} /><button onClick={()=>void analyseRepository()} disabled={repoBusy || !repoUrl.trim()}>{repoBusy ? 'Analyzing GitHub…' : 'Analyze repository'}</button>{repoResult && <div className="tutor-error">⚠ {repoResult}</div>}{repoRubric && <div className="result-panel"><b>{repoRubric.repository.fullName} · {repoRubric.portfolioScore}% portfolio score</b><p>{repoRubric.repository.description}</p><small>{repoRubric.repository.language} · {repoRubric.repository.stars} stars · README {repoRubric.repository.readmePresent ? 'found' : 'missing'}</small><div className="quality-bars">{repoRubric.rubric.map((item:any)=><span key={item.label}>{item.label} <b>{item.score}%</b><i style={{width:`${item.score}%`}} /><small>{item.tip}</small></span>)}</div></div>}</section>}
      {show('analytics') && <section className="hub-card"><h2>📈 Your learning intelligence</h2><div className="analytics-score"><div><strong>{Math.min(100,completedLessons.length*4+20)}</strong><span>Readiness score</span></div><p>Your score combines completed lessons, assessments, projects and placement activity.</p></div><div className="completion-chart" aria-label="Learner completion chart">{Array.from({length:7},(_,index)=>Math.min(100, Math.max(8, completedLessons.length * (index + 1) * 3))).map((value,index)=><div key={index}><i style={{height:`${value}%`}} /><small>{['M','T','W','T','F','S','S'][index]}</small></div>)}</div>{[['Learning progress',Math.min(100,completedLessons.length*5)],['Assessment strength',assessmentAttempts[0]?.score || state.quizScore],['Portfolio readiness',Math.min(100,state.projects.length*25)],['Placement preparation',Math.round(state.placementTasks.length/6*100)]].map(([label,value])=><div className="analytics-row" key={String(label)}><span>{label}</span><b>{value}%</b><div className="progress-track"><i style={{width:`${value}%`}} /></div></div>)}</section>}
      {show('skill-tree') && (() => { const nodes=[['Foundations',completedLessons.length>=1,'Finish one roadmap lesson'],['Core concepts',completedLessons.length>=3,'Finish 3 lessons'],['Applied practice',assessmentAttempts.some(item=>item.score>=50),'Score at least 50% in an assessment'],['Portfolio project',state.projects.length>=1,'Add one GitHub project'],['Interview ready',interviewAnswer.length>=120,'Save a detailed mock-interview answer']]; return <section className="hub-card hub-wide skill-constellation-card"><div className="skill-constellation" aria-hidden="true"><i/><i/><i/><i/><i/></div><h2>🌳 {profile?.careerPathId ? 'Your role skill tree' : 'Engineering skill tree'}</h2><p>Every milestone below is calculated from your actual lesson, assessment, project, and interview activity.</p><div className="skill-tree">{nodes.map(([skill,unlocked,requirement])=><article key={String(skill)} className={unlocked ? 'unlocked' : ''}><span>{unlocked ? '✓' : '🔒'}</span><b>{skill}</b><small>{unlocked ? 'Unlocked from your activity' : String(requirement)}</small></article>)}</div></section>; })()}
      {show('adaptive-practice') && <section className="hub-card"><h2>🎯 Adaptive practice</h2><p>{assessmentAttempts.length ? 'Your last assessment is used to guide this validation scenario.' : 'Take an assessment first for a more personalised difficulty signal.'}</p><div className="question-box"><h3>Before shipping an engineering solution, what should you do first?</h3></div><label className="choice-row"><input type="radio" name="adaptive" checked={practiceChoice==='validate'} onChange={()=>setPracticeChoice('validate')} /> Define a measurable validation test</label><label className="choice-row"><input type="radio" name="adaptive" checked={practiceChoice==='measure'} onChange={()=>setPracticeChoice('measure')} /> Ask for general feedback only</label><label className="choice-row"><input type="radio" name="adaptive" checked={practiceChoice==='guess'} onChange={()=>setPracticeChoice('guess')} /> Assume it works after implementation</label><button onClick={()=>void runAdaptivePractice()}>Check and adapt</button>{practiceResult && <div className="result-panel"><b>Mistake analysis</b><p>{practiceResult}</p><button onClick={()=>{setPracticeChoice('');setPracticeResult('');}}>Try another attempt</button></div>}</section>}
      {show('weakness-heatmap') && (() => { const signals=[['Core concepts',Math.min(100,completedLessons.length*34),'quiz'],['Applied practice',assessmentAttempts[0]?.score || 0,'adaptive-practice'],['Portfolio evidence',Math.min(100,state.projects.length*60),'projects'],['Interview communication',Math.min(100,Math.round(interviewAnswer.length/2)),'interviews']]; return <section className="hub-card"><h2>🗺️ Roadmap weakness heatmap</h2><p>Scores are calculated from your current progress, assessment, portfolio, and interview activity—not random labels.</p><div className="heatmap-grid">{signals.map(([skill,score,target])=>{const numeric=Number(score);const status=numeric<40?'focus':numeric<75?'steady':'strong';return <article className={status} key={String(skill)}><b>{skill}</b><strong>{numeric}%</strong><span>{status==='focus'?'Focus next':status==='steady'?'Building':'Strong'}</span><button onClick={()=>onFeatureChange?.(String(target))}>Open action →</button></article>;})}</div></section>; })()}
      {show('daily-challenge') && <section className="daily-challenge-board"><header><div><span>🎯</span><h2>Daily challenges</h2></div><p>Complete today’s role-relevant tasks to earn XP · Progress: {dailyTasks.filter(task => state.completedChallenges.includes(task.id)).length}/3</p></header><div className="daily-task-list">{dailyTasks.map(task => { const done = state.completedChallenges.includes(task.id); return <article className={done ? 'done' : ''} key={task.id}><span className="daily-task-icon">{done ? '✓' : task.icon}</span><div><b>{task.title}</b><small>+{task.xp} XP</small></div><button className="daily-go" onClick={() => setDailyFocus(task.id)}>Go</button><button className="daily-complete" onClick={() => void completeChallenge(task.id)} disabled={done}>{done ? 'Completed ✓' : 'Mark done'}</button></article>; })}</div>{dailyFocus && <div className="result-panel"><b>Today’s focused task</b><p>{dailyFocus==='daily-concept' ? 'Choose one lesson concept. Write its definition, one engineering example, and one measurable check in your Notes.' : dailyFocus==='daily-practice' ? 'Define a measurable test for something you are building: input, expected result, and pass condition.' : 'Improve one project README: add the problem, setup steps, a result screenshot, or a clear GitHub link.'}</p><button onClick={()=>setDailyFocus('')}>Back to challenges</button></div>}{dailyError && <div className="tutor-error">⚠ {dailyError}</div>}<footer><span>⚡ {dailyStatus?.streak ? `${dailyStatus.streak}-day saved streak · ` : ''}Keep a short daily learning streak—consistency builds real engineering skill.</span><b>{dailyStatus?.xp ?? dailyTasks.filter(task => state.completedChallenges.includes(task.id)).reduce((sum, task) => sum + task.xp, 0)} XP today</b></footer></section>}
      {show('ai-summarizer') && <section className="hub-card hub-wide"><h2>🧾 AI engineering summarizer</h2><textarea value={smartTopic} onChange={e=>setSmartTopic(e.target.value)} placeholder="Paste notes, a documentation section, or a concept to summarize…" /><button onClick={()=>void generateStudyAsset('summary')} disabled={smartBusy || !smartTopic.trim()}>{smartBusy ? 'Creating summary…' : 'Summarize for revision'}</button>{smartResult && <pre className="smart-output">{smartResult}</pre>}{tutorError && <div className="tutor-error">⚠ {tutorError}</div>}</section>}
      {show('cheatsheet') && <section className="hub-card hub-wide"><h2>🗒️ Cheatsheet generator</h2><input value={smartTopic} onChange={e=>setSmartTopic(e.target.value)} placeholder="Example: REST API authentication, Ohm’s law, SQL joins" /><button onClick={()=>void generateStudyAsset('cheatsheet')} disabled={smartBusy || !smartTopic.trim()}>{smartBusy ? 'Creating cheatsheet…' : 'Generate cheatsheet'}</button>{smartResult && <pre className="smart-output">{smartResult}</pre>}{tutorError && <div className="tutor-error">⚠ {tutorError}</div>}</section>}
      {show('career-explorer') && <section className="hub-card hub-wide"><h2>🧭 Career explorer</h2><h3>{profile?.careerPathId ? 'Your selected engineering role' : 'Choose a role to personalize this view'}</h3><p>Build evidence in four areas: technical foundations, applied projects, communication, and a professional GitHub/portfolio presence.</p><div className="career-points"><article><b>Learn</b><span>Finish core modules in your roadmap</span></article><article><b>Build</b><span>Create two role-relevant projects</span></article><article><b>Show</b><span>Document work on GitHub and your resume</span></article><article><b>Practise</b><span>Complete mock interviews and placement tasks</span></article></div><Link className="hub-link" to="/profile">Review or change selected role →</Link></section>}
      {show('job-readiness') && <section className="hub-card"><h2>📐 Job readiness predictor</h2>{(()=>{const lessons=Math.min(100,completedLessons.length*10); const assessment=assessmentAttempts[0]?.score || state.quizScore; const portfolio=Math.min(100,state.projects.length*50); const placement=Math.round(state.placementTasks.length/6*100); const score=Math.round((lessons+assessment+portfolio+placement)/4); return <><strong className="big-number">{score}%</strong><p>Transparent estimate from learning, assessment, portfolio and placement signals.</p>{[['Lessons',lessons],['Assessment',assessment],['Portfolio',portfolio],['Placement',placement]].map(([label,value])=><div className="analytics-row" key={String(label)}><span>{label}</span><b>{value}%</b><div className="progress-track"><i style={{width:`${value}%`}} /></div></div>)}</>;})()}</section>}
      {show('doubt-upload') && <section className="hub-card hub-wide"><h2>📷 AI code, diagram & circuit doubts</h2><p>Attach an image or PDF and describe the issue. Gemini Vision analyzes the reference in memory; it is not stored publicly.</p><div className="doubt-grid"><label>Doubt type<select value={doubtKind} onChange={e=>setDoubtKind(e.target.value)}><option>Code issue</option><option>Circuit diagram</option><option>Engineering drawing</option><option>Maths / calculation</option><option>Project design</option></select></label><label>Reference file (optional)<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" onChange={e=>selectDoubtReference(e.target.files?.[0])} /><small>{doubtFileName || 'Nothing attached'}</small></label></div>{doubtPreview && <img className="doubt-preview" src={doubtPreview} alt="Local doubt reference preview" />}<textarea value={doubtDescription} onChange={e=>setDoubtDescription(e.target.value)} placeholder="What did you expect? What actually happened? Include values, error text, circuit components, or constraints…" /><button onClick={()=>void askDoubtTutor()} disabled={doubtBusy || !doubtDescription.trim()}>{doubtBusy ? 'Reviewing your doubt…' : doubtFile ? 'Analyze with Gemini Vision' : 'Ask engineering tutor'}</button>{doubtResult && <pre className="smart-output">{doubtResult}</pre>}</section>}
    </div>{details && activeFeature !== 'ai-tutor' && <aside className="feature-guide"><section><span className="dashboard-kicker">HOW IT WORKS</span><h2>Get the best result</h2><ol>{details.steps.map(step=><li key={step}>{step}</li>)}</ol></section><section className="feature-tip"><b>💡 Engineer’s tip</b><p>{details.tip}</p></section><section><span className="dashboard-kicker">YOUR DATA</span><p className="privacy-note">Your activity in this local version is stored only in this browser.</p></section></aside>}</div>
  </div>;
}
